/**
 * Inviting someone to a circuit by message.
 *
 * Same shape as the Snake challenge (src/game/challenge.ts), deliberately: an invite is just a
 * chat message. There is no pending-invite table, nothing to expire, and nothing to reconcile
 * if it is never answered — the message IS the invite, it lives in the conversation where you
 * would expect to find it, and it works from a phone or a notification.
 *
 * The link carries the circuit's existing join code, which is the same code the Circuits panel
 * already offers to copy. So this adds no new way in: it is the code you would have pasted
 * yourself, wrapped in something tappable.
 */

/** Join codes are generated by the database: letters and digits, nothing exotic. */
const CODE_RE = /#circuit\?join=([A-Za-z0-9_-]+)/
/**
 * Same thing, but swallowing any scheme+host in front of it, so stripping the link out of a
 * sentence doesn't leave a bare origin sitting in the middle of it.
 */
const LINK_RE = /(?:https?:\/\/\S*?)?#circuit\?join=[A-Za-z0-9_-]+/g

export function circuitJoinLink(code: string): string {
  return `${location.origin}${location.pathname}#circuit?join=${encodeURIComponent(code)}`
}

/**
 * The text that gets posted. Plain English with the link on its own line: if it ever renders as
 * raw text — an old client, a notification preview, a copy into a text message — it still reads
 * as an invitation and the link is still tappable.
 */
export function circuitInviteMessage(code: string, circuitName?: string): string {
  const which = circuitName ? ` “${circuitName}”` : ''
  return `🏆 Join my circuit${which}:\n${circuitJoinLink(code)}`
}

/** The join code inside a message, or null if this isn't an invite. */
export function circuitJoinCodeOf(body: string): string | null {
  const m = CODE_RE.exec(body)
  if (!m) return null
  try {
    return decodeURIComponent(m[1])
  } catch {
    return m[1]
  }
}

/**
 * The message with the link taken out, so a card can show the human part without repeating a
 * URL underneath it. Null when nothing readable is left.
 */
export function circuitInviteText(body: string): string | null {
  const rest = body
    .replace(LINK_RE, '')
    .replace(/[ \t]+/g, ' ')
    .trim()
  return rest.length ? rest : null
}

/* ── arriving on one ────────────────────────────────────────────────────────
 * The link lands on `#circuit?join=CODE`, which can be opened while signed out — an invite
 * arrives by DM, but the device it gets tapped on may not have a session. So the code is moved
 * out of the URL into a one-shot stash on arrival and only spent once there is somebody to
 * spend it for. Out of the URL matters: left there, a refresh or a back button would try to
 * join all over again, and the code would sit in the address bar to be copied by anyone
 * looking over a shoulder.
 */

const STASH_KEY = 'circuit_pending_join'

/** Is there a code in the current URL? Cheap enough to ask before deciding which tab opens. */
export function hasJoinCodeInUrl(): boolean {
  return !!new URLSearchParams(window.location.hash.split('?')[1] ?? '').get('join')
}

/** Move a code out of the URL and into the stash. Safe to call repeatedly. */
export function parkJoinCode(): void {
  const q = new URLSearchParams(window.location.hash.split('?')[1] ?? '')
  const code = q.get('join')
  if (!code) return
  try {
    sessionStorage.setItem(STASH_KEY, code)
  } catch {
    /* private mode: the join below still works, it just won't survive a sign-in */
  }
  q.delete('join')
  const rest = q.toString()
  // replaceState rather than assigning location.hash: this is tidying the address bar, and it
  // should not add a history entry you can go "back" into and re-trigger.
  history.replaceState(null, '', `${window.location.pathname}#circuit${rest ? `?${rest}` : ''}`)
}

/** Spend it. Returns the code once and never again. */
export function takeJoinCode(): string | null {
  parkJoinCode()
  try {
    const code = sessionStorage.getItem(STASH_KEY)
    if (code) sessionStorage.removeItem(STASH_KEY)
    return code
  } catch {
    return null
  }
}
