// AUTO-GENERATED by scripts/gen-public-seed.mjs — do not edit by hand.
// One person's slice of the live Circuit: their board and logs, only the reviews they rated and
// only their own score on each, and the shared pool as titles. This is the public demo data
// shown to signed-out visitors, so it must never carry anybody else — the generator asserts that
// before it writes. Regenerate with: node scripts/gen-public-seed.mjs --write
import type { CircuitState } from './types'

export const publicSeed: CircuitState = {
  people: [
    {
      id: '2',
      name: 'Evan',
      color: '#7c6af7',
      goal: 100,
      exercises: [
        {
          id: '6',
          cat: 'walk',
          col: 3,
          row: 0,
          mult: 16,
          name: 'Miles walked',
          unit: 'mi',
        },
        {
          id: '4',
          cat: 'arms',
          col: 0,
          row: 1,
          mult: 1,
          name: 'Weights',
          unit: 'reps',
        },
        {
          id: '2',
          cat: 'arms',
          col: 0,
          row: 2,
          mult: 1,
          name: 'Pushups',
          unit: 'reps',
        },
        {
          id: '1',
          cat: 'arms',
          col: 0,
          row: 3,
          mult: 2,
          name: 'Pullups',
          unit: 'reps',
        },
        {
          id: '3ea4deac-f835-4851-8985-053a3a492355',
          cat: 'other',
          col: 3,
          row: 1,
          mult: 11,
          name: 'reading',
          unit: 'pages',
        },
        {
          id: '5',
          cat: 'run',
          col: 2,
          row: 0,
          mult: 32,
          name: 'Miles ran',
          unit: 'mi',
        },
        {
          id: '3',
          cat: 'core',
          col: 2,
          row: 1,
          mult: 10,
          name: 'Core / Plank',
          unit: 'min',
        },
        {
          id: '7',
          cat: 'legs',
          col: 4,
          row: 0,
          mult: 1,
          name: 'Legs',
          unit: 'reps',
        },
        {
          id: '8a133ef7-aff4-41de-9b4b-e239b1ef32c5',
          cat: 'other',
          col: 1,
          row: 0,
          mult: 5,
          name: 'Beers Drank',
          unit: 'other',
        },
        {
          id: '92cf4a29-75c0-42a1-ac2c-91fb593ef38b',
          cat: 'core',
          col: 1,
          row: 1,
          mult: 1,
          name: 'Bicycle situps',
          unit: 'reps',
        },
        {
          id: '5f125603-9e10-4210-b9ac-0c26bf62235c',
          cat: 'core',
          col: 1,
          row: 2,
          mult: 1,
          name: 'AB wheel',
          unit: 'reps',
        },
        {
          id: '93f49833-a135-4f2e-b540-a1539c50a145',
          cat: 'other',
          col: 5,
          row: 0,
          mult: 50,
          name: 'Distance swimming',
          unit: 'mile',
        },
      ],
      colLabels: ['Arms', 'Core', 'Run', 'Walk', 'Legs', 'swim'],
    },
  ],
  logs: [
    {
      id: '2018',
      personId: '2',
      date: '2026-04-05',
      entries: [
        {
          eid: '__total__',
          val: 171.72,
        },
      ],
    },
    {
      id: '2019',
      personId: '2',
      date: '2026-04-06',
      entries: [
        {
          eid: '__total__',
          val: 42.16,
        },
      ],
    },
    {
      id: '2020',
      personId: '2',
      date: '2026-04-10',
      entries: [
        {
          eid: '__total__',
          val: 100.44,
        },
      ],
    },
    {
      id: '2021',
      personId: '2',
      date: '2026-04-21',
      entries: [
        {
          eid: '__total__',
          val: 100.44,
        },
      ],
    },
    {
      id: '2022',
      personId: '2',
      date: '2026-04-23',
      entries: [
        {
          eid: '2',
          val: 30,
        },
      ],
    },
    {
      id: '2023',
      personId: '2',
      date: '2026-04-27',
      entries: [
        {
          eid: '__total__',
          val: 118.16,
        },
      ],
    },
    {
      id: '2024',
      personId: '2',
      date: '2026-04-28',
      entries: [
        {
          eid: '__total__',
          val: 116.44,
        },
      ],
    },
    {
      id: '2025',
      personId: '2',
      date: '2026-04-29',
      entries: [
        {
          eid: '__total__',
          val: 25.6,
        },
      ],
    },
    {
      id: '2026',
      personId: '2',
      date: '2026-04-30',
      entries: [
        {
          eid: '__total__',
          val: 26.4,
        },
      ],
    },
    {
      id: '2077',
      personId: '2',
      date: '2026-05-02',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2078',
      personId: '2',
      date: '2026-05-03',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2079',
      personId: '2',
      date: '2026-05-04',
      entries: [
        {
          eid: '__total__',
          val: 28,
        },
      ],
    },
    {
      id: '2080',
      personId: '2',
      date: '2026-05-05',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2081',
      personId: '2',
      date: '2026-05-06',
      entries: [
        {
          eid: '__total__',
          val: 20,
        },
      ],
    },
    {
      id: '2082',
      personId: '2',
      date: '2026-05-07',
      entries: [
        {
          eid: '__total__',
          val: 32,
        },
      ],
    },
    {
      id: '2083',
      personId: '2',
      date: '2026-05-08',
      entries: [
        {
          eid: '__total__',
          val: 8,
        },
      ],
    },
    {
      id: '2084',
      personId: '2',
      date: '2026-05-09',
      entries: [
        {
          eid: '__total__',
          val: 228.88,
        },
      ],
    },
    {
      id: '2085',
      personId: '2',
      date: '2026-05-10',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2086',
      personId: '2',
      date: '2026-05-11',
      entries: [
        {
          eid: '__total__',
          val: 28,
        },
      ],
    },
    {
      id: '2087',
      personId: '2',
      date: '2026-05-13',
      entries: [
        {
          eid: '__total__',
          val: 38,
        },
      ],
    },
    {
      id: '2088',
      personId: '2',
      date: '2026-05-14',
      entries: [
        {
          eid: '__total__',
          val: 106.8,
        },
      ],
    },
    {
      id: '2089',
      personId: '2',
      date: '2026-05-15',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2090',
      personId: '2',
      date: '2026-05-16',
      entries: [
        {
          eid: '__total__',
          val: 224.88,
        },
      ],
    },
    {
      id: '2091',
      personId: '2',
      date: '2026-05-17',
      entries: [
        {
          eid: '__total__',
          val: 16,
        },
      ],
    },
    {
      id: '2092',
      personId: '2',
      date: '2026-05-18',
      entries: [
        {
          eid: '__total__',
          val: 157.8,
        },
      ],
    },
    {
      id: '2093',
      personId: '2',
      date: '2026-05-19',
      entries: [
        {
          eid: '__total__',
          val: 20,
        },
      ],
    },
    {
      id: '2094',
      personId: '2',
      date: '2026-05-20',
      entries: [
        {
          eid: '__total__',
          val: 44,
        },
      ],
    },
    {
      id: '2095',
      personId: '2',
      date: '2026-05-22',
      entries: [
        {
          eid: '__total__',
          val: 100.44,
        },
      ],
    },
    {
      id: '2096',
      personId: '2',
      date: '2026-05-23',
      entries: [
        {
          eid: '__total__',
          val: 28,
        },
      ],
    },
    {
      id: '2097',
      personId: '2',
      date: '2026-05-24',
      entries: [
        {
          eid: '__total__',
          val: 20,
        },
      ],
    },
    {
      id: '2098',
      personId: '2',
      date: '2026-05-25',
      entries: [
        {
          eid: '__total__',
          val: 32,
        },
      ],
    },
    {
      id: '2099',
      personId: '2',
      date: '2026-05-26',
      entries: [
        {
          eid: '__total__',
          val: 36,
        },
      ],
    },
    {
      id: 'c1014254-8b1c-4cb8-8f3c-14b0b60b43c2',
      personId: '2',
      date: '2026-06-15',
      entries: [
        {
          eid: '2',
          val: 10,
        },
        {
          eid: '5',
          val: 3.5,
        },
        {
          eid: '6',
          val: 0.87,
        },
      ],
    },
    {
      id: '20250723020',
      personId: '2',
      date: '2025-07-23',
      entries: [
        {
          eid: '__total__',
          val: 160,
        },
      ],
    },
    {
      id: '20250725020',
      personId: '2',
      date: '2025-07-25',
      entries: [
        {
          eid: '__total__',
          val: 135,
        },
      ],
    },
    {
      id: '20250726020',
      personId: '2',
      date: '2025-07-26',
      entries: [
        {
          eid: '__total__',
          val: 110,
        },
      ],
    },
    {
      id: '20250727020',
      personId: '2',
      date: '2025-07-27',
      entries: [
        {
          eid: '__total__',
          val: 115.32,
        },
      ],
    },
    {
      id: '20250728020',
      personId: '2',
      date: '2025-07-28',
      entries: [
        {
          eid: '__total__',
          val: 154,
        },
      ],
    },
    {
      id: '20250729020',
      personId: '2',
      date: '2025-07-29',
      entries: [
        {
          eid: '__total__',
          val: 437.2,
        },
      ],
    },
    {
      id: '20250730020',
      personId: '2',
      date: '2025-07-30',
      entries: [
        {
          eid: '__total__',
          val: 254,
        },
      ],
    },
    {
      id: '20250731020',
      personId: '2',
      date: '2025-07-31',
      entries: [
        {
          eid: '__total__',
          val: 105,
        },
      ],
    },
    {
      id: '20250801020',
      personId: '2',
      date: '2025-08-01',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250802020',
      personId: '2',
      date: '2025-08-02',
      entries: [
        {
          eid: '__total__',
          val: 130,
        },
      ],
    },
    {
      id: '20250803020',
      personId: '2',
      date: '2025-08-03',
      entries: [
        {
          eid: '__total__',
          val: 110,
        },
      ],
    },
    {
      id: '20250804020',
      personId: '2',
      date: '2025-08-04',
      entries: [
        {
          eid: '__total__',
          val: 245,
        },
      ],
    },
    {
      id: '20250806020',
      personId: '2',
      date: '2025-08-06',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250807020',
      personId: '2',
      date: '2025-08-07',
      entries: [
        {
          eid: '__total__',
          val: 156.2,
        },
      ],
    },
    {
      id: '20250808020',
      personId: '2',
      date: '2025-08-08',
      entries: [
        {
          eid: '__total__',
          val: 116,
        },
      ],
    },
    {
      id: '20250809020',
      personId: '2',
      date: '2025-08-09',
      entries: [
        {
          eid: '__total__',
          val: 155,
        },
      ],
    },
    {
      id: '20250810020',
      personId: '2',
      date: '2025-08-10',
      entries: [
        {
          eid: '__total__',
          val: 40,
        },
      ],
    },
    {
      id: '20250811020',
      personId: '2',
      date: '2025-08-11',
      entries: [
        {
          eid: '__total__',
          val: 175.2,
        },
      ],
    },
    {
      id: '20250812020',
      personId: '2',
      date: '2025-08-12',
      entries: [
        {
          eid: '__total__',
          val: 185.44,
        },
      ],
    },
    {
      id: '20250813020',
      personId: '2',
      date: '2025-08-13',
      entries: [
        {
          eid: '__total__',
          val: 120,
        },
      ],
    },
    {
      id: '20250814020',
      personId: '2',
      date: '2025-08-14',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250815020',
      personId: '2',
      date: '2025-08-15',
      entries: [
        {
          eid: '__total__',
          val: 105,
        },
      ],
    },
    {
      id: '20250816020',
      personId: '2',
      date: '2025-08-16',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250817020',
      personId: '2',
      date: '2025-08-17',
      entries: [
        {
          eid: '__total__',
          val: 330,
        },
      ],
    },
    {
      id: '20250818020',
      personId: '2',
      date: '2025-08-18',
      entries: [
        {
          eid: '__total__',
          val: 255.44,
        },
      ],
    },
    {
      id: '20250819020',
      personId: '2',
      date: '2025-08-19',
      entries: [
        {
          eid: '__total__',
          val: 120,
        },
      ],
    },
    {
      id: '20250820020',
      personId: '2',
      date: '2025-08-20',
      entries: [
        {
          eid: '__total__',
          val: 105,
        },
      ],
    },
    {
      id: '20250821020',
      personId: '2',
      date: '2025-08-21',
      entries: [
        {
          eid: '__total__',
          val: 30,
        },
      ],
    },
    {
      id: '20250822020',
      personId: '2',
      date: '2025-08-22',
      entries: [
        {
          eid: '__total__',
          val: 115,
        },
      ],
    },
    {
      id: '20250823020',
      personId: '2',
      date: '2025-08-23',
      entries: [
        {
          eid: '__total__',
          val: 110,
        },
      ],
    },
    {
      id: '20250824020',
      personId: '2',
      date: '2025-08-24',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250826020',
      personId: '2',
      date: '2025-08-26',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250827020',
      personId: '2',
      date: '2025-08-27',
      entries: [
        {
          eid: '__total__',
          val: 141,
        },
      ],
    },
    {
      id: '20250828020',
      personId: '2',
      date: '2025-08-28',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250830020',
      personId: '2',
      date: '2025-08-30',
      entries: [
        {
          eid: '__total__',
          val: 135,
        },
      ],
    },
    {
      id: '20250831020',
      personId: '2',
      date: '2025-08-31',
      entries: [
        {
          eid: '__total__',
          val: 102,
        },
      ],
    },
    {
      id: '20250901020',
      personId: '2',
      date: '2025-09-01',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250902020',
      personId: '2',
      date: '2025-09-02',
      entries: [
        {
          eid: '__total__',
          val: 360,
        },
      ],
    },
    {
      id: '20250903020',
      personId: '2',
      date: '2025-09-03',
      entries: [
        {
          eid: '__total__',
          val: 0.1,
        },
      ],
    },
    {
      id: '20250904020',
      personId: '2',
      date: '2025-09-04',
      entries: [
        {
          eid: '__total__',
          val: 115,
        },
      ],
    },
    {
      id: '20250905020',
      personId: '2',
      date: '2025-09-05',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250906020',
      personId: '2',
      date: '2025-09-06',
      entries: [
        {
          eid: '__total__',
          val: 151,
        },
      ],
    },
    {
      id: '20250907020',
      personId: '2',
      date: '2025-09-07',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250908020',
      personId: '2',
      date: '2025-09-08',
      entries: [
        {
          eid: '__total__',
          val: 251.516,
        },
      ],
    },
    {
      id: '20250909020',
      personId: '2',
      date: '2025-09-09',
      entries: [
        {
          eid: '__total__',
          val: 200,
        },
      ],
    },
    {
      id: '20250910020',
      personId: '2',
      date: '2025-09-10',
      entries: [
        {
          eid: '__total__',
          val: 0.1,
        },
      ],
    },
    {
      id: '20250911020',
      personId: '2',
      date: '2025-09-11',
      entries: [
        {
          eid: '__total__',
          val: 60,
        },
      ],
    },
    {
      id: '20250912020',
      personId: '2',
      date: '2025-09-12',
      entries: [
        {
          eid: '__total__',
          val: 0.1,
        },
      ],
    },
    {
      id: '20250913020',
      personId: '2',
      date: '2025-09-13',
      entries: [
        {
          eid: '__total__',
          val: 150,
        },
      ],
    },
    {
      id: '20250914020',
      personId: '2',
      date: '2025-09-14',
      entries: [
        {
          eid: '__total__',
          val: 100.44,
        },
      ],
    },
    {
      id: '20250915020',
      personId: '2',
      date: '2025-09-15',
      entries: [
        {
          eid: '__total__',
          val: 300,
        },
      ],
    },
    {
      id: '20250916020',
      personId: '2',
      date: '2025-09-16',
      entries: [
        {
          eid: '__total__',
          val: 0.1,
        },
      ],
    },
    {
      id: '20250917020',
      personId: '2',
      date: '2025-09-17',
      entries: [
        {
          eid: '__total__',
          val: 250,
        },
      ],
    },
    {
      id: '20250918020',
      personId: '2',
      date: '2025-09-18',
      entries: [
        {
          eid: '__total__',
          val: 250,
        },
      ],
    },
    {
      id: '20250919020',
      personId: '2',
      date: '2025-09-19',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250920020',
      personId: '2',
      date: '2025-09-20',
      entries: [
        {
          eid: '__total__',
          val: 200,
        },
      ],
    },
    {
      id: '20250921020',
      personId: '2',
      date: '2025-09-21',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250922020',
      personId: '2',
      date: '2025-09-22',
      entries: [
        {
          eid: '__total__',
          val: 150,
        },
      ],
    },
    {
      id: '20250924020',
      personId: '2',
      date: '2025-09-24',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250925020',
      personId: '2',
      date: '2025-09-25',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250926020',
      personId: '2',
      date: '2025-09-26',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20250928020',
      personId: '2',
      date: '2025-09-28',
      entries: [
        {
          eid: '__total__',
          val: 51,
        },
      ],
    },
    {
      id: '20250930020',
      personId: '2',
      date: '2025-09-30',
      entries: [
        {
          eid: '__total__',
          val: 180.24,
        },
      ],
    },
    {
      id: '20251002020',
      personId: '2',
      date: '2025-10-02',
      entries: [
        {
          eid: '__total__',
          val: 200,
        },
      ],
    },
    {
      id: '20251003020',
      personId: '2',
      date: '2025-10-03',
      entries: [
        {
          eid: '__total__',
          val: 205,
        },
      ],
    },
    {
      id: '20251004020',
      personId: '2',
      date: '2025-10-04',
      entries: [
        {
          eid: '__total__',
          val: 200,
        },
      ],
    },
    {
      id: '20251006020',
      personId: '2',
      date: '2025-10-06',
      entries: [
        {
          eid: '__total__',
          val: 200,
        },
      ],
    },
    {
      id: '20251010020',
      personId: '2',
      date: '2025-10-10',
      entries: [
        {
          eid: '__total__',
          val: 162,
        },
      ],
    },
    {
      id: '20251012020',
      personId: '2',
      date: '2025-10-12',
      entries: [
        {
          eid: '__total__',
          val: 197.316,
        },
      ],
    },
    {
      id: '20251015020',
      personId: '2',
      date: '2025-10-15',
      entries: [
        {
          eid: '__total__',
          val: 329.6,
        },
      ],
    },
    {
      id: '20251016020',
      personId: '2',
      date: '2025-10-16',
      entries: [
        {
          eid: '__total__',
          val: 136.08,
        },
      ],
    },
    {
      id: '20251020020',
      personId: '2',
      date: '2025-10-20',
      entries: [
        {
          eid: '__total__',
          val: 200,
        },
      ],
    },
    {
      id: '20251021020',
      personId: '2',
      date: '2025-10-21',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20251022020',
      personId: '2',
      date: '2025-10-22',
      entries: [
        {
          eid: '__total__',
          val: 140,
        },
      ],
    },
    {
      id: '20251023020',
      personId: '2',
      date: '2025-10-23',
      entries: [
        {
          eid: '__total__',
          val: 162,
        },
      ],
    },
    {
      id: '20251024020',
      personId: '2',
      date: '2025-10-24',
      entries: [
        {
          eid: '__total__',
          val: 140,
        },
      ],
    },
    {
      id: '20251025020',
      personId: '2',
      date: '2025-10-25',
      entries: [
        {
          eid: '__total__',
          val: 101,
        },
      ],
    },
    {
      id: '20251026020',
      personId: '2',
      date: '2025-10-26',
      entries: [
        {
          eid: '__total__',
          val: 205,
        },
      ],
    },
    {
      id: '20251027020',
      personId: '2',
      date: '2025-10-27',
      entries: [
        {
          eid: '__total__',
          val: 30,
        },
      ],
    },
    {
      id: '20251029020',
      personId: '2',
      date: '2025-10-29',
      entries: [
        {
          eid: '__total__',
          val: 10,
        },
      ],
    },
    {
      id: '20251030020',
      personId: '2',
      date: '2025-10-30',
      entries: [
        {
          eid: '__total__',
          val: 32.4,
        },
      ],
    },
    {
      id: '20251102020',
      personId: '2',
      date: '2025-11-02',
      entries: [
        {
          eid: '__total__',
          val: 220,
        },
      ],
    },
    {
      id: '20251103020',
      personId: '2',
      date: '2025-11-03',
      entries: [
        {
          eid: '__total__',
          val: 120,
        },
      ],
    },
    {
      id: '20251105020',
      personId: '2',
      date: '2025-11-05',
      entries: [
        {
          eid: '__total__',
          val: 279.716,
        },
      ],
    },
    {
      id: '20251107020',
      personId: '2',
      date: '2025-11-07',
      entries: [
        {
          eid: '__total__',
          val: 132,
        },
      ],
    },
    {
      id: '20251108020',
      personId: '2',
      date: '2025-11-08',
      entries: [
        {
          eid: '__total__',
          val: 120,
        },
      ],
    },
    {
      id: '20251111020',
      personId: '2',
      date: '2025-11-11',
      entries: [
        {
          eid: '__total__',
          val: 173.12,
        },
      ],
    },
    {
      id: '20251112020',
      personId: '2',
      date: '2025-11-12',
      entries: [
        {
          eid: '__total__',
          val: 156,
        },
      ],
    },
    {
      id: '20251114020',
      personId: '2',
      date: '2025-11-14',
      entries: [
        {
          eid: '__total__',
          val: 106,
        },
      ],
    },
    {
      id: '20251115020',
      personId: '2',
      date: '2025-11-15',
      entries: [
        {
          eid: '__total__',
          val: 102,
        },
      ],
    },
    {
      id: '20251118020',
      personId: '2',
      date: '2025-11-18',
      entries: [
        {
          eid: '__total__',
          val: 22,
        },
      ],
    },
    {
      id: '20251120020',
      personId: '2',
      date: '2025-11-20',
      entries: [
        {
          eid: '__total__',
          val: 122,
        },
      ],
    },
    {
      id: '20251121020',
      personId: '2',
      date: '2025-11-21',
      entries: [
        {
          eid: '__total__',
          val: 203,
        },
      ],
    },
    {
      id: '20251122020',
      personId: '2',
      date: '2025-11-22',
      entries: [
        {
          eid: '__total__',
          val: 253.656,
        },
      ],
    },
    {
      id: '20251123020',
      personId: '2',
      date: '2025-11-23',
      entries: [
        {
          eid: '__total__',
          val: 221.94,
        },
      ],
    },
    {
      id: '20251128020',
      personId: '2',
      date: '2025-11-28',
      entries: [
        {
          eid: '__total__',
          val: 213,
        },
      ],
    },
    {
      id: '20251129020',
      personId: '2',
      date: '2025-11-29',
      entries: [
        {
          eid: '__total__',
          val: 110,
        },
      ],
    },
    {
      id: '20251130020',
      personId: '2',
      date: '2025-11-30',
      entries: [
        {
          eid: '__total__',
          val: 130,
        },
      ],
    },
    {
      id: '20251201020',
      personId: '2',
      date: '2025-12-01',
      entries: [
        {
          eid: '__total__',
          val: 32,
        },
      ],
    },
    {
      id: '20251202020',
      personId: '2',
      date: '2025-12-02',
      entries: [
        {
          eid: '__total__',
          val: 10,
        },
      ],
    },
    {
      id: '20251203020',
      personId: '2',
      date: '2025-12-03',
      entries: [
        {
          eid: '__total__',
          val: 123,
        },
      ],
    },
    {
      id: '20251204020',
      personId: '2',
      date: '2025-12-04',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20251209020',
      personId: '2',
      date: '2025-12-09',
      entries: [
        {
          eid: '__total__',
          val: 204,
        },
      ],
    },
    {
      id: '20251211020',
      personId: '2',
      date: '2025-12-11',
      entries: [
        {
          eid: '__total__',
          val: 100,
        },
      ],
    },
    {
      id: '20251212020',
      personId: '2',
      date: '2025-12-12',
      entries: [
        {
          eid: '__total__',
          val: 42,
        },
      ],
    },
    {
      id: '20251214020',
      personId: '2',
      date: '2025-12-14',
      entries: [
        {
          eid: '__total__',
          val: 102,
        },
      ],
    },
    {
      id: '20251216020',
      personId: '2',
      date: '2025-12-16',
      entries: [
        {
          eid: '__total__',
          val: 102,
        },
      ],
    },
    {
      id: '20251227020',
      personId: '2',
      date: '2025-12-27',
      entries: [
        {
          eid: '__total__',
          val: 22,
        },
      ],
    },
    {
      id: '20260101020',
      personId: '2',
      date: '2026-01-01',
      entries: [
        {
          eid: '__total__',
          val: 106.8,
        },
      ],
    },
    {
      id: '20260103020',
      personId: '2',
      date: '2026-01-03',
      entries: [
        {
          eid: '__total__',
          val: 106.8,
        },
      ],
    },
    {
      id: '20260121020',
      personId: '2',
      date: '2026-01-21',
      entries: [
        {
          eid: '__total__',
          val: 16.8,
        },
      ],
    },
    {
      id: '20260201020',
      personId: '2',
      date: '2026-02-01',
      entries: [
        {
          eid: '__total__',
          val: 11.2,
        },
      ],
    },
    {
      id: '20260202020',
      personId: '2',
      date: '2026-02-02',
      entries: [
        {
          eid: '__total__',
          val: 53.4,
        },
      ],
    },
    {
      id: 'l-2-2026-06-19',
      personId: '2',
      date: '2026-06-19',
      entries: [
        {
          eid: '6',
          val: 2,
        },
      ],
    },
    {
      id: '472c94eb-c26f-420c-8d68-c4853fc75289',
      personId: '2',
      date: '2026-06-20',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
        {
          eid: '8a133ef7-aff4-41de-9b4b-e239b1ef32c5',
          val: 2,
        },
      ],
    },
    {
      id: 'l-2-2026-06-30',
      personId: '2',
      date: '2026-06-30',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-02',
      personId: '2',
      date: '2026-07-02',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-06-29',
      personId: '2',
      date: '2026-06-29',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-28',
      personId: '2',
      date: '2026-06-28',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-27',
      personId: '2',
      date: '2026-06-27',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-06-26',
      personId: '2',
      date: '2026-06-26',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-25',
      personId: '2',
      date: '2026-06-25',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-24',
      personId: '2',
      date: '2026-06-24',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-23',
      personId: '2',
      date: '2026-06-23',
      entries: [
        {
          eid: '6',
          val: 1.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-18',
      personId: '2',
      date: '2026-06-18',
      entries: [
        {
          eid: '6',
          val: 0.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-22',
      personId: '2',
      date: '2026-06-22',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-06-21',
      personId: '2',
      date: '2026-06-21',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-06-17',
      personId: '2',
      date: '2026-06-17',
      entries: [
        {
          eid: '6',
          val: 3.6,
        },
      ],
    },
    {
      id: 'l-2-2026-06-14',
      personId: '2',
      date: '2026-06-14',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-06-13',
      personId: '2',
      date: '2026-06-13',
      entries: [
        {
          eid: '6',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-12',
      personId: '2',
      date: '2026-06-12',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-11',
      personId: '2',
      date: '2026-06-11',
      entries: [
        {
          eid: '6',
          val: 1.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-10',
      personId: '2',
      date: '2026-06-10',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-06-09',
      personId: '2',
      date: '2026-06-09',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-06-06',
      personId: '2',
      date: '2026-06-06',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-08',
      personId: '2',
      date: '2026-06-08',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-03',
      personId: '2',
      date: '2026-06-03',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-06-01',
      personId: '2',
      date: '2026-06-01',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-05-29',
      personId: '2',
      date: '2026-05-29',
      entries: [
        {
          eid: '6',
          val: 5.5,
        },
      ],
    },
    {
      id: 'l-2-2026-06-05',
      personId: '2',
      date: '2026-06-05',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
      ],
    },
    {
      id: 'l-2-2026-05-31',
      personId: '2',
      date: '2026-05-31',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-06-02',
      personId: '2',
      date: '2026-06-02',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-05-30',
      personId: '2',
      date: '2026-05-30',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-05-28',
      personId: '2',
      date: '2026-05-28',
      entries: [
        {
          eid: '6',
          val: 3.7,
        },
      ],
    },
    {
      id: 'l-2-2026-05-27',
      personId: '2',
      date: '2026-05-27',
      entries: [
        {
          eid: '6',
          val: 4.4,
        },
      ],
    },
    {
      id: 'l-2-2026-07-27',
      personId: '2',
      date: '2026-07-27',
      entries: [
        {
          eid: '6',
          val: 6.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-26',
      personId: '2',
      date: '2026-07-26',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-07',
      personId: '2',
      date: '2026-07-07',
      entries: [
        {
          eid: '6',
          val: 1,
        },
      ],
    },
    {
      id: 'l-2-2026-07-06',
      personId: '2',
      date: '2026-07-06',
      entries: [
        {
          eid: '6',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-05',
      personId: '2',
      date: '2026-07-05',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-07-25',
      personId: '2',
      date: '2026-07-25',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-07-24',
      personId: '2',
      date: '2026-07-24',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-07-04',
      personId: '2',
      date: '2026-07-04',
      entries: [
        {
          eid: '6',
          val: 5.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-03',
      personId: '2',
      date: '2026-07-03',
      entries: [
        {
          eid: '6',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-01',
      personId: '2',
      date: '2026-07-01',
      entries: [
        {
          eid: '6',
          val: 3,
        },
        {
          eid: '5',
          val: 3.21,
        },
      ],
    },
    {
      id: 'l-2-2026-07-08',
      personId: '2',
      date: '2026-07-08',
      entries: [
        {
          eid: '6',
          val: 3,
        },
        {
          eid: '2',
          val: 50,
        },
      ],
    },
    {
      id: 'l-2-2026-07-09',
      personId: '2',
      date: '2026-07-09',
      entries: [
        {
          eid: '6',
          val: 2,
        },
      ],
    },
    {
      id: 'l-2-2026-08-14',
      personId: '2',
      date: '2026-08-14',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-07-23',
      personId: '2',
      date: '2026-07-23',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-18',
      personId: '2',
      date: '2026-08-18',
      entries: [
        {
          eid: '6',
          val: 1,
        },
      ],
    },
    {
      id: 'l-2-2026-08-17',
      personId: '2',
      date: '2026-08-17',
      entries: [
        {
          eid: '6',
          val: 1.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-16',
      personId: '2',
      date: '2026-08-16',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-08-15',
      personId: '2',
      date: '2026-08-15',
      entries: [
        {
          eid: '6',
          val: 6,
        },
      ],
    },
    {
      id: 'l-2-2026-07-22',
      personId: '2',
      date: '2026-07-22',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-13',
      personId: '2',
      date: '2026-08-13',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-12',
      personId: '2',
      date: '2026-08-12',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-21',
      personId: '2',
      date: '2026-07-21',
      entries: [
        {
          eid: '6',
          val: 2,
        },
      ],
    },
    {
      id: 'l-2-2026-08-19',
      personId: '2',
      date: '2026-08-19',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-10',
      personId: '2',
      date: '2026-08-10',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-09',
      personId: '2',
      date: '2026-08-09',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-08-08',
      personId: '2',
      date: '2026-08-08',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-07',
      personId: '2',
      date: '2026-08-07',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-08-06',
      personId: '2',
      date: '2026-08-06',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-05',
      personId: '2',
      date: '2026-08-05',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-03',
      personId: '2',
      date: '2026-08-03',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-02',
      personId: '2',
      date: '2026-08-02',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-01',
      personId: '2',
      date: '2026-08-01',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-07-31',
      personId: '2',
      date: '2026-07-31',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-07-30',
      personId: '2',
      date: '2026-07-30',
      entries: [
        {
          eid: '6',
          val: 5.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-29',
      personId: '2',
      date: '2026-07-29',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-07-28',
      personId: '2',
      date: '2026-07-28',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-20',
      personId: '2',
      date: '2026-07-20',
      entries: [
        {
          eid: '6',
          val: 8.3,
        },
      ],
    },
    {
      id: 'l-2-2026-07-19',
      personId: '2',
      date: '2026-07-19',
      entries: [
        {
          eid: '6',
          val: 4,
        },
        {
          eid: '2',
          val: 5,
        },
        {
          eid: '5',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-18',
      personId: '2',
      date: '2026-07-18',
      entries: [
        {
          eid: '6',
          val: 4.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-15',
      personId: '2',
      date: '2026-07-15',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-13',
      personId: '2',
      date: '2026-07-13',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-07-12',
      personId: '2',
      date: '2026-07-12',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-07-11',
      personId: '2',
      date: '2026-07-11',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-07-10',
      personId: '2',
      date: '2026-07-10',
      entries: [
        {
          eid: '6',
          val: 1.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-20',
      personId: '2',
      date: '2026-08-20',
      entries: [
        {
          eid: '6',
          val: 2,
        },
      ],
    },
    {
      id: 'l-2-2026-09-12',
      personId: '2',
      date: '2026-09-12',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-09-11',
      personId: '2',
      date: '2026-09-11',
      entries: [
        {
          eid: '5',
          val: 5,
        },
        {
          eid: '93f49833-a135-4f2e-b540-a1539c50a145',
          val: 1,
        },
      ],
    },
    {
      id: 'l-2-2026-09-10',
      personId: '2',
      date: '2026-09-10',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-09-07',
      personId: '2',
      date: '2026-09-07',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-09-09',
      personId: '2',
      date: '2026-09-09',
      entries: [
        {
          eid: '6',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-09-08',
      personId: '2',
      date: '2026-09-08',
      entries: [
        {
          eid: '6',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-09-06',
      personId: '2',
      date: '2026-09-06',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-09-05',
      personId: '2',
      date: '2026-09-05',
      entries: [
        {
          eid: '6',
          val: 4,
        },
      ],
    },
    {
      id: 'l-2-2026-09-04',
      personId: '2',
      date: '2026-09-04',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-09-03',
      personId: '2',
      date: '2026-09-03',
      entries: [
        {
          eid: '6',
          val: 1,
        },
      ],
    },
    {
      id: 'l-2-2026-09-01',
      personId: '2',
      date: '2026-09-01',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-09-02',
      personId: '2',
      date: '2026-09-02',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-31',
      personId: '2',
      date: '2026-08-31',
      entries: [
        {
          eid: '6',
          val: 2.5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-30',
      personId: '2',
      date: '2026-08-30',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-29',
      personId: '2',
      date: '2026-08-29',
      entries: [
        {
          eid: '6',
          val: 2,
        },
      ],
    },
    {
      id: 'l-2-2026-08-28',
      personId: '2',
      date: '2026-08-28',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-27',
      personId: '2',
      date: '2026-08-27',
      entries: [
        {
          eid: '6',
          val: 1,
        },
      ],
    },
    {
      id: 'l-2-2026-08-23',
      personId: '2',
      date: '2026-08-23',
      entries: [
        {
          eid: '6',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-26',
      personId: '2',
      date: '2026-08-26',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-22',
      personId: '2',
      date: '2026-08-22',
      entries: [
        {
          eid: '6',
          val: 5,
        },
      ],
    },
    {
      id: 'l-2-2026-08-24',
      personId: '2',
      date: '2026-08-24',
      entries: [
        {
          eid: '6',
          val: 3,
        },
      ],
    },
    {
      id: 'l-2-2026-08-21',
      personId: '2',
      date: '2026-08-21',
      entries: [
        {
          eid: '6',
          val: 3.5,
        },
      ],
    },
  ],
  movies: [
    {
      id: 'm99f1ae2a-9ad1-45dd-ad7c-909e6862387d',
      title: 'X2',
      kind: 'movie',
      date: '2026-06-22',
      ratings: {
        '2': {
          score: 84,
        },
      },
    },
    {
      id: 'mb40b9534-f716-4089-80b7-85f5c6d8b7c2',
      title: 'Backrooms',
      kind: 'movie',
      date: '2026-07-03',
      rt: '74',
      ratings: {
        '2': {
          score: 75,
        },
      },
    },
    {
      id: 'mdc2e9280-6e6b-40bf-9c8b-c5b120216e8f',
      title: 'Kill Bill 2',
      kind: 'movie',
      date: '2026-07-21',
      ratings: {
        '2': {
          score: 83,
        },
      },
    },
    {
      id: 'mbf6dca61-5c75-4985-88d5-3370f9dfbcfb',
      title: 'Obsession',
      kind: 'movie',
      date: '2026-07-11',
      rt: '94',
      ratings: {
        '2': {
          score: 94,
        },
      },
    },
    {
      id: 'maa8bfa82-a971-4e4f-b8f5-6761c9d55208',
      title: 'Mistfall Hunter',
      kind: 'game',
      date: '2026-08-10',
      ratings: {
        '2': {
          score: 94,
        },
      },
    },
    {
      id: 'mf608580b-539a-4cfd-8b4e-9c81dc4e68be',
      title: 'Water',
      kind: 'drink',
      date: '2026-09-13',
      ratings: {
        '2': {
          score: 100,
        },
      },
    },
    {
      id: 'm23be5752-098d-4add-93fe-331125f5a49c',
      title: 'Monolith',
      kind: 'movie',
      date: '2026-07-13',
      rt: '54',
      ratings: {
        '2': {
          score: 65,
        },
      },
    },
    {
      id: 'md6f5bb64-b1aa-4476-b6f7-05f807f3c7b7',
      title: 'Los Toritos',
      kind: 'food',
      date: '2026-08-14',
      ratings: {
        '2': {
          score: 93,
        },
      },
    },
    {
      id: 'm131',
      title: 'Mortal Kombat II',
      kind: 'movie',
      ratings: {
        '2': {
          score: 87,
        },
      },
    },
    {
      id: 'm132',
      title: 'They Will Kill You',
      kind: 'movie',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
    {
      id: 'm6',
      title: 'The Dark Knight',
      kind: 'movie',
      rt: '94%',
      ratings: {
        '2': {
          score: 95,
        },
      },
    },
    {
      id: 'm7010f80f-90b6-4324-954f-eb1ecaba2c48',
      title: 'Subservience',
      kind: 'movie',
      date: '2026-06-19',
      rt: '37',
      ratings: {
        '2': {
          score: 79,
        },
      },
    },
    {
      id: 'mdc37adf9-157b-4e38-8a88-fc707ad85dcc',
      title: 'WorldBreaker',
      kind: 'movie',
      date: '2026-07-16',
      ratings: {
        '2': {
          score: 40,
        },
      },
    },
    {
      id: 'm30351fab-7f4f-4173-8520-6bc5488fe688',
      title: '10 Cloverfield Lane',
      kind: 'movie',
      date: '2026-06-28',
      rt: '68',
      ratings: {
        '2': {
          score: 81,
        },
      },
    },
    {
      id: 'm7',
      title: 'Parasite',
      kind: 'movie',
      rt: '99%',
      ratings: {
        '2': {
          score: 94,
        },
      },
    },
    {
      id: 'm9',
      title: 'Avatar: The Way of Water',
      kind: 'movie',
      rt: '76%',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
    {
      id: 'm12',
      title: 'Mad Max: Fury Road',
      kind: 'movie',
      rt: '97%',
      ratings: {
        '2': {
          score: 89,
        },
      },
    },
    {
      id: 'm13',
      title: 'Mad Max Furiosa',
      kind: 'movie',
      rt: '90%',
      ratings: {
        '2': {
          score: 93,
        },
      },
    },
    {
      id: 'm15',
      title: 'Barbarian',
      kind: 'movie',
      rt: '92%',
      ratings: {
        '2': {
          score: 93,
        },
      },
    },
    {
      id: 'm16',
      title: 'Nope',
      kind: 'movie',
      rt: '83%',
      ratings: {
        '2': {
          score: 94,
        },
      },
    },
    {
      id: 'm18',
      title: 'Avatar: Fire and Ash',
      kind: 'movie',
      ratings: {
        '2': {
          score: 85,
        },
      },
    },
    {
      id: 'm23',
      title: 'One Battle After Another',
      kind: 'movie',
      rt: '94%',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
    {
      id: 'm30',
      title: 'Heretic',
      kind: 'movie',
      rt: '90%',
      ratings: {
        '2': {
          score: 91,
        },
      },
    },
    {
      id: 'm31',
      title: 'The Emperor&#39;s New Groove',
      kind: 'movie',
      rt: '86%',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
    {
      id: 'm32',
      title: 'Weapons',
      kind: 'movie',
      rt: '93%',
      ratings: {
        '2': {
          score: 91,
        },
      },
    },
    {
      id: 'm33',
      title: 'Evil Dead 2013',
      kind: 'movie',
      ratings: {
        '2': {
          score: 87,
        },
      },
    },
    {
      id: 'm35',
      title: 'Blade Runner 2049 (2017)',
      kind: 'movie',
      rt: '88%',
      ratings: {
        '2': {
          score: 89,
        },
      },
    },
    {
      id: 'm39',
      title: 'Bugonia',
      kind: 'movie',
      rt: '84%',
      ratings: {
        '2': {
          score: 91,
        },
      },
    },
    {
      id: 'm40',
      title: 'Hero',
      kind: 'movie',
      rt: '94%',
      ratings: {
        '2': {
          score: 88,
        },
      },
    },
    {
      id: 'm43',
      title: 'Us',
      kind: 'movie',
      rt: '93%',
      ratings: {
        '2': {
          score: 84,
        },
      },
    },
    {
      id: 'm44',
      title: 'Wake Up Dead Man: A Knives Out Mystery',
      kind: 'movie',
      rt: '94%',
      ratings: {
        '2': {
          score: 86,
        },
      },
    },
    {
      id: 'm46',
      title: 'Talk to me',
      kind: 'movie',
      rt: '94%',
      ratings: {
        '2': {
          score: 86,
        },
      },
    },
    {
      id: 'm54',
      title: 'Alita Battle Angel',
      kind: 'movie',
      rt: '61%',
      ratings: {
        '2': {
          score: 84,
        },
      },
    },
    {
      id: 'm55',
      title: 'NehZha2',
      kind: 'movie',
      rt: '92%',
      ratings: {
        '2': {
          score: 78,
        },
      },
    },
    {
      id: 'm56',
      title: 'Sinners',
      kind: 'movie',
      rt: '97%',
      ratings: {
        '2': {
          score: 82,
        },
      },
    },
    {
      id: 'm60',
      title: 'Predator: Badlands',
      kind: 'movie',
      rt: '86%',
      ratings: {
        '2': {
          score: 87,
        },
      },
    },
    {
      id: 'm63',
      title: 'KPop DH',
      kind: 'movie',
      rt: '96%',
      ratings: {
        '2': {
          score: 80,
        },
      },
    },
    {
      id: 'm65',
      title: 'The Revenant',
      kind: 'movie',
      rt: '78%',
      ratings: {
        '2': {
          score: 79,
        },
      },
    },
    {
      id: 'm66',
      title: 'Companion',
      kind: 'movie',
      ratings: {
        '2': {
          score: 80,
        },
      },
    },
    {
      id: 'm67',
      title: 'Anaconda',
      kind: 'movie',
      rt: '48%',
      ratings: {
        '2': {
          score: 85,
        },
      },
    },
    {
      id: 'm71',
      title: 'Alien Romulus',
      kind: 'movie',
      rt: '80%',
      ratings: {
        '2': {
          score: 79,
        },
      },
    },
    {
      id: 'm74',
      title: 'Pluribus S1',
      kind: 'movie',
      rt: '98%',
      ratings: {
        '2': {
          score: 82,
        },
      },
    },
    {
      id: 'm75',
      title: 'Frankenstein',
      kind: 'movie',
      rt: '85%',
      ratings: {
        '2': {
          score: 80,
        },
      },
    },
    {
      id: 'm78',
      title: 'The Batman',
      kind: 'movie',
      rt: '85%',
      ratings: {
        '2': {
          score: 74,
        },
      },
    },
    {
      id: 'm81',
      title: 'Prey',
      kind: 'movie',
      rt: '94%',
      ratings: {
        '2': {
          score: 75,
        },
      },
    },
    {
      id: 'm85',
      title: 'Good Fortune',
      kind: 'movie',
      rt: '79%',
      ratings: {
        '2': {
          score: 79,
        },
      },
    },
    {
      id: 'm86',
      title: 'Sisu',
      kind: 'movie',
      rt: '94%',
      ratings: {
        '2': {
          score: 77,
        },
      },
    },
    {
      id: 'm87',
      title: 'Blade 1',
      kind: 'movie',
      rt: '59%',
      ratings: {
        '2': {
          score: 83,
        },
      },
    },
    {
      id: 'm94',
      title: 'Van Helsing',
      kind: 'movie',
      rt: '34%',
      ratings: {
        '2': {
          score: 73,
        },
      },
    },
    {
      id: 'm96',
      title: 'Chainsaw Man: Reze Arc',
      kind: 'movie',
      rt: '96%',
      ratings: {
        '2': {
          score: 78,
        },
      },
    },
    {
      id: 'm97',
      title: 'Jumper',
      kind: 'movie',
      rt: '15%',
      ratings: {
        '2': {
          score: 75,
        },
      },
    },
    {
      id: 'm99',
      title: 'Speak No Evil (English)',
      kind: 'movie',
      rt: '83%',
      ratings: {
        '2': {
          score: 73,
        },
      },
    },
    {
      id: 'm100',
      title: 'League of Extrordinary GM',
      kind: 'movie',
      rt: '17%',
      ratings: {
        '2': {
          score: 72,
        },
      },
    },
    {
      id: 'm102',
      title: 'The Substance',
      kind: 'movie',
      rt: '89%',
      ratings: {
        '2': {
          score: 78,
        },
      },
    },
    {
      id: 'm103',
      title: 'mummy',
      kind: 'movie',
      ratings: {
        '2': {
          score: 70,
        },
      },
    },
    {
      id: 'm104',
      title: 'Mystery Men',
      kind: 'movie',
      rt: '59%',
      ratings: {
        '2': {
          score: 71,
        },
      },
    },
    {
      id: 'm107',
      title: 'Nobody2',
      kind: 'movie',
      rt: '77%',
      ratings: {
        '2': {
          score: 75,
        },
      },
    },
    {
      id: 'm110',
      title: 'Good Boy',
      kind: 'movie',
      rt: '90%',
      ratings: {
        '2': {
          score: 67,
        },
      },
    },
    {
      id: 'm111',
      title: 'Caught Stealing',
      kind: 'movie',
      rt: '84%',
      ratings: {
        '2': {
          score: 72,
        },
      },
    },
    {
      id: 'm112',
      title: 'Nobody',
      kind: 'movie',
      rt: '83%',
      ratings: {
        '2': {
          score: 65,
        },
      },
    },
    {
      id: 'm113',
      title: 'Minecraft Movie',
      kind: 'movie',
      rt: '47%',
      ratings: {
        '2': {
          score: 74,
        },
      },
    },
    {
      id: 'm115',
      title: 'Sisu 2',
      kind: 'movie',
      rt: '95%',
      ratings: {
        '2': {
          score: 61,
        },
      },
    },
    {
      id: 'm116',
      title: 'Mickey 17',
      kind: 'movie',
      rt: '78%',
      ratings: {
        '2': {
          score: 64,
        },
      },
    },
    {
      id: 'm118',
      title: 'The Fantastic Four: First Steps',
      kind: 'movie',
      rt: '86%',
      ratings: {
        '2': {
          score: 55,
        },
      },
    },
    {
      id: 'm119',
      title: 'Five Nights At Freddy&#39;s 2',
      kind: 'movie',
      rt: '16%',
      ratings: {
        '2': {
          score: 66,
        },
      },
    },
    {
      id: 'm120',
      title: 'I, Frankenstein',
      kind: 'movie',
      rt: '5%',
      ratings: {
        '2': {
          score: 57,
        },
      },
    },
    {
      id: 'm122',
      title: 'StrangerThings S5',
      kind: 'movie',
      rt: '84%',
      ratings: {
        '2': {
          score: 67,
        },
      },
    },
    {
      id: 'm123',
      title: 'TRON:Ares',
      kind: 'movie',
      rt: '53%',
      ratings: {
        '2': {
          score: 69,
        },
      },
    },
    {
      id: 'm124',
      title: 'CRIME 101',
      kind: 'movie',
      ratings: {
        '2': {
          score: 62,
        },
      },
    },
    {
      id: 'm125',
      title: 'The Watchers',
      kind: 'movie',
      rt: '32%',
      ratings: {
        '2': {
          score: 61,
        },
      },
    },
    {
      id: 'm126',
      title: 'Eddington',
      kind: 'movie',
      rt: '69%',
      ratings: {
        '2': {
          score: 51,
        },
      },
    },
    {
      id: 'm128',
      title: 'The Running Man 2025',
      kind: 'movie',
      rt: '63%',
      ratings: {
        '2': {
          score: 64,
        },
      },
    },
    {
      id: 'm8d4803db-fe99-4655-afcc-d345e8ea88b4',
      title: '10 Cloverfield',
      kind: 'movie',
      date: '2026-06-29',
      ratings: {
        '2': {
          score: 78,
        },
      },
    },
    {
      id: 'mc5d678d9-290e-4276-a032-d4fa0df67a11',
      title: 'Kill Bill',
      kind: 'movie',
      date: '2026-07-21',
      ratings: {
        '2': {
          score: 80,
        },
      },
    },
  ],
  watchlist: [
    {
      id: 'wl76564ef0-a3a8-4e13-8166-e4972d3924e4',
      title: 'League',
      kind: 'game',
    },
    {
      id: 'w0',
      title: 'The Big Lebowski',
      rt: '94%',
      kind: 'movie',
    },
    {
      id: 'w1',
      title: '300',
      rt: '88%',
      kind: 'movie',
    },
    {
      id: 'w2',
      title: 'No Country for Old Men',
      rt: '86%',
      kind: 'movie',
    },
    {
      id: 'w3',
      title: 'Ex Machina',
      rt: '86%',
      kind: 'movie',
    },
    {
      id: 'w4',
      title: '28 Days Later',
      rt: '85%',
      kind: 'movie',
    },
    {
      id: 'w5',
      title: 'The Revenant',
      rt: '84%',
      kind: 'movie',
    },
    {
      id: 'w6',
      title: 'Upgrade',
      rt: '83%',
      kind: 'movie',
    },
    {
      id: 'w7',
      title: 'Arrival',
      rt: '82%',
      kind: 'movie',
    },
    {
      id: 'w8',
      title: 'Arcadian',
      rt: '81%',
      kind: 'movie',
    },
    {
      id: 'w9',
      title: 'Blade Runner 2049',
      rt: '81%',
      kind: 'movie',
    },
    {
      id: 'w10',
      title: 'Dredd',
      rt: '78%',
      kind: 'movie',
    },
    {
      id: 'w11',
      title: '28 Weeks Later',
      rt: '74%',
      kind: 'movie',
    },
    {
      id: 'w12',
      title: 'Snowpiercer',
      rt: '73%',
      kind: 'movie',
    },
    {
      id: 'w13',
      title: 'The Girl with All the Gifts',
      rt: '72%',
      kind: 'movie',
    },
    {
      id: 'w14',
      title: 'Wyrmwood: Road of the Dead',
      rt: '70%',
      kind: 'movie',
    },
    {
      id: 'w15',
      title: 'The Lobster',
      rt: '69%',
      kind: 'movie',
    },
    {
      id: 'w16',
      title: 'Event Horizon',
      rt: '68%',
      kind: 'movie',
    },
    {
      id: 'w17',
      title: 'Hereditary',
      rt: '67%',
      kind: 'movie',
    },
    {
      id: 'w18',
      title: 'Annihilation',
      rt: '65%',
      kind: 'movie',
    },
    {
      id: 'w19',
      title: 'Blade (Trilogy Average)',
      rt: '64%',
      kind: 'movie',
    },
    {
      id: 'wl02c9f935-baf0-46c4-bbfb-063b862410b2',
      title: 'League of Legends',
      kind: 'game',
    },
    {
      id: 'w32',
      title: 'Season of the Witch',
      rt: '18%',
      kind: 'movie',
    },
    {
      id: 'w33',
      title: 'The Incredibles',
      kind: 'movie',
    },
    {
      id: 'wl9b476840-156f-4cb1-b486-4a8533eddf86',
      title: 'test 1',
      kind: 'game',
    },
    {
      id: 'wl5fca035a-f7e5-41ed-ae5e-8f5f3555e01e',
      title: 'Overwatch',
      kind: 'game',
    },
    {
      id: 'wl0bf6a056-9f38-4d4f-b2ac-33f7148eb219',
      title: 'Golf with friends',
      kind: 'game',
    },
    {
      id: 'w21',
      title: 'The Road',
      rt: '58%',
      kind: 'movie',
    },
    {
      id: 'w22',
      title: 'Dracula Untold',
      rt: '49%',
      kind: 'movie',
    },
    {
      id: 'w23',
      title: 'Outlander (2008)',
      rt: '46%',
      kind: 'movie',
    },
    {
      id: 'w24',
      title: 'Solomon Kane',
      rt: '45%',
      kind: 'movie',
    },
    {
      id: 'w25',
      title: 'The Canal',
      rt: '44%',
      kind: 'movie',
    },
    {
      id: 'w26',
      title: 'The Awakening',
      rt: '43%',
      kind: 'movie',
    },
    {
      id: 'w27',
      title: 'Sahara',
      rt: '42%',
      kind: 'movie',
    },
    {
      id: 'w28',
      title: 'The Hallow',
      rt: '41%',
      kind: 'movie',
    },
    {
      id: 'w29',
      title: 'I, Frankenstein',
      rt: '35%',
      kind: 'movie',
    },
    {
      id: 'w30',
      title: 'Legion',
      rt: '27%',
      kind: 'movie',
    },
    {
      id: 'w31',
      title: 'The Pyramid',
      rt: '20%',
      kind: 'movie',
    },
    {
      id: 'w34',
      title: 'terminators',
      kind: 'movie',
    },
    {
      id: 'w35',
      title: 'resident evils',
      kind: 'movie',
    },
    {
      id: 'w36',
      title: 'king kong',
      kind: 'movie',
    },
    {
      id: 'w37',
      title: '10000 BC',
      kind: 'movie',
    },
    {
      id: 'w38',
      title: 'excalibur',
      kind: 'movie',
    },
    {
      id: 'w39',
      title: 'looper',
      kind: 'movie',
    },
    {
      id: 'w40',
      title: 'Bring her back',
      kind: 'movie',
    },
    {
      id: 'w41',
      title: 'prometheus',
      kind: 'movie',
    },
    {
      id: 'w42',
      title: 'Shanghai Knights',
      kind: 'movie',
    },
    {
      id: 'w43',
      title: 'Shanghai Noon',
      kind: 'movie',
    },
    {
      id: 'w44',
      title: 'Dark Knight',
      kind: 'movie',
    },
    {
      id: 'w45',
      title: 'soylent green',
      kind: 'movie',
    },
    {
      id: 'w46',
      title: 'oddity',
      kind: 'movie',
    },
    {
      id: 'w47',
      title: 'companion',
      kind: 'movie',
    },
    {
      id: 'w48',
      title: 'ghost in the shell',
      kind: 'movie',
    },
    {
      id: 'w49',
      title: 'sunshine',
      kind: 'movie',
    },
    {
      id: 'w50',
      title: 'deer hunter',
      kind: 'movie',
    },
    {
      id: 'w51',
      title: 'Evil dead 2013',
      kind: 'movie',
    },
    {
      id: 'w52',
      title: 'Austin Powers',
      kind: 'movie',
    },
    {
      id: 'w53',
      title: 'Waiting',
      kind: 'movie',
    },
    {
      id: 'w54',
      title: 'Dodgeball',
      kind: 'movie',
    },
    {
      id: 'w55',
      title: 'Die another day',
      kind: 'movie',
    },
    {
      id: 'w56',
      title: 'Coyotes',
      kind: 'movie',
    },
    {
      id: 'w57',
      title: 'The Shawshank Redemption',
      kind: 'movie',
    },
    {
      id: 'w58',
      title: 'Tenet',
      kind: 'movie',
    },
    {
      id: 'w59',
      title: 'shrek',
      kind: 'movie',
    },
    {
      id: 'w60',
      title: 'spy kids',
      kind: 'movie',
    },
    {
      id: 'w61',
      title: 'The Invisible Man',
      kind: 'movie',
    },
    {
      id: 'w62',
      title: 'Cast Away',
      kind: 'movie',
    },
    {
      id: 'w63',
      title: 'The Good, The Bad, The Ugly',
      kind: 'movie',
    },
    {
      id: 'w64',
      title: 'Fight Club',
      kind: 'movie',
    },
    {
      id: 'w65',
      title: 'The Matrix',
      kind: 'movie',
    },
    {
      id: 'w66',
      title: 'Interstellar',
      kind: 'movie',
    },
    {
      id: 'w67',
      title: 'American History X',
      kind: 'movie',
    },
    {
      id: 'w68',
      title: 'The Usual Suspects',
      kind: 'movie',
    },
    {
      id: 'w69',
      title: 'Memento',
      kind: 'movie',
    },
    {
      id: 'w70',
      title: '2001: A Space Oddessy',
      kind: 'movie',
    },
    {
      id: 'w71',
      title: 'Indiana Jones Movies',
      kind: 'movie',
    },
    {
      id: 'w72',
      title: 'Wolf of Wall Street',
      kind: 'movie',
    },
    {
      id: 'w73',
      title: 'There will be Blood',
      kind: 'movie',
    },
    {
      id: 'w74',
      title: 'Shutter Island',
      kind: 'movie',
    },
    {
      id: 'w75',
      title: '12 years a slave',
      kind: 'movie',
    },
    {
      id: 'w76',
      title: 'million dollar baby',
      kind: 'movie',
    },
    {
      id: 'w77',
      title: 'The Iron Giant',
      kind: 'movie',
    },
    {
      id: 'w78',
      title: 'Gone Girl',
      kind: 'movie',
    },
    {
      id: 'w79',
      title: 'The Sixth Sense',
      kind: 'movie',
    },
    {
      id: 'w80',
      title: 'Resevoir Dogs',
      kind: 'movie',
    },
    {
      id: 'w81',
      title: 'Eternal Sunshine of the Spotless Mind',
      kind: 'movie',
    },
    {
      id: 'w83',
      title: 'The Silence of the Lambs',
      kind: 'movie',
    },
    {
      id: 'w84',
      title: 'Se7en',
      kind: 'movie',
    },
    {
      id: 'w85',
      title: 'Requiem for a Dream',
      kind: 'movie',
    },
    {
      id: 'w86',
      title: 'The Departed',
      kind: 'movie',
    },
    {
      id: 'w87',
      title: 'Gangs of New York',
      kind: 'movie',
    },
    {
      id: 'w88',
      title: 'Training Day',
      kind: 'movie',
    },
    {
      id: 'w89',
      title: 'The Patriot',
      kind: 'movie',
    },
    {
      id: 'w90',
      title: 'The Last of the Mohicans',
      kind: 'movie',
    },
    {
      id: 'w91',
      title: 'Pulp fiction',
      kind: 'movie',
    },
    {
      id: 'w92',
      title: 'Minority report',
      kind: 'movie',
    },
    {
      id: 'w93',
      title: 'Neighbours',
      kind: 'movie',
    },
    {
      id: 'w94',
      title: 'Superbad',
      kind: 'movie',
    },
    {
      id: 'w95',
      title: 'They will kill you',
      kind: 'movie',
    },
    {
      id: 'w96',
      title: 'GZ -1',
      kind: 'movie',
    },
    {
      id: 'w97',
      title: 'BrodrickZilla',
      kind: 'movie',
    },
    {
      id: 'w98',
      title: 'Breaking BadZilla',
      kind: 'movie',
    },
    {
      id: 'w99',
      title: 'Boardroom Simulator',
      kind: 'movie',
    },
    {
      id: 'w100',
      title: 'kinda of kindness',
      kind: 'movie',
    },
    {
      id: 'wl4c5e955d-5140-4d38-9ef8-9d88efa21b1f',
      title: 'Mistfall Hunters',
      kind: 'game',
    },
    {
      id: 'wl2f5b827e-813e-4353-a920-18ee8bf917da',
      title: 'Gartic Phone',
      kind: 'game',
    },
    {
      id: 'wl16286903-d964-4f6c-9e28-e86d72f558e0',
      title: 'test 1',
      kind: 'game',
    },
    {
      id: 'wl0add69be-7b46-45a4-bec3-97905aa0f4d4',
      title: 'Mistfall Hunters',
      kind: 'game',
    },
    {
      id: 'wl4b2c2677-78e1-4c38-802a-0a02d1526ee4',
      title: 'Apex',
      kind: 'game',
    },
    {
      id: 'wlf0df1de5-628a-40a1-822a-bcc495fc429c',
      title: 'Gartic Phone',
      kind: 'game',
    },
  ],
}
