// AUTO-GENERATED by scripts/gen-public-seed.mjs — do not edit by hand.
// Evan-only (pid '2') slice of the Circuit, derived from seed.ts at build-authoring
// time. This is the public demo data shown to signed-out visitors. Crucially it does NOT
// import seed.ts, so the rest of the group's real data never reaches the client bundle —
// the full group lives only in Supabase. Regenerate with: node scripts/gen-public-seed.mjs
import type { CircuitState } from './types'

export const publicSeed: CircuitState = {
  people: [
    {
      id: '2',
      name: 'Evan',
      color: '#7c6af7',
      goal: 100,
      exercises: [
        {
          id: '1',
          name: 'Pullups',
          unit: 'reps',
          mult: 2,
          cat: 'arms',
          col: 0,
          row: 0,
        },
        {
          id: '2',
          name: 'Pushups',
          unit: 'reps',
          mult: 1,
          cat: 'arms',
          col: 0,
          row: 1,
        },
        {
          id: '3',
          name: 'Core / Plank',
          unit: 'min',
          mult: 10,
          cat: 'core',
          col: 1,
          row: 0,
        },
        {
          id: '4',
          name: 'Weights',
          unit: 'reps',
          mult: 1,
          cat: 'arms',
          col: 0,
          row: 2,
        },
        {
          id: '5',
          name: 'Miles ran',
          unit: 'mi',
          mult: 32,
          cat: 'run',
          col: 2,
          row: 0,
        },
        {
          id: '6',
          name: 'Miles walked',
          unit: 'mi',
          mult: 16,
          cat: 'walk',
          col: 3,
          row: 0,
        },
        {
          id: '7',
          name: 'Legs',
          unit: 'reps',
          mult: 1,
          cat: 'legs',
          col: 4,
          row: 0,
        },
      ],
      colLabels: ['Arms', 'Core', 'Run', 'Walk', 'Legs'],
    },
  ],
  logs: [
    {
      id: '2018',
      personId: '2',
      date: '2026-04-05',
      entries: [
        {
          eid: '__total__',
          val: 171.72,
        },
      ],
    },
    {
      id: '2019',
      personId: '2',
      date: '2026-04-06',
      entries: [
        {
          eid: '__total__',
          val: 42.16,
        },
      ],
    },
    {
      id: '2020',
      personId: '2',
      date: '2026-04-10',
      entries: [
        {
          eid: '__total__',
          val: 100.44,
        },
      ],
    },
    {
      id: '2021',
      personId: '2',
      date: '2026-04-21',
      entries: [
        {
          eid: '__total__',
          val: 100.44,
        },
      ],
    },
    {
      id: '2022',
      personId: '2',
      date: '2026-04-23',
      entries: [
        {
          eid: '2',
          val: 30,
        },
      ],
    },
    {
      id: '2023',
      personId: '2',
      date: '2026-04-27',
      entries: [
        {
          eid: '__total__',
          val: 118.16,
        },
      ],
    },
    {
      id: '2024',
      personId: '2',
      date: '2026-04-28',
      entries: [
        {
          eid: '__total__',
          val: 116.44,
        },
      ],
    },
    {
      id: '2025',
      personId: '2',
      date: '2026-04-29',
      entries: [
        {
          eid: '__total__',
          val: 25.6,
        },
      ],
    },
    {
      id: '2026',
      personId: '2',
      date: '2026-04-30',
      entries: [
        {
          eid: '__total__',
          val: 26.4,
        },
      ],
    },
    {
      id: '2077',
      personId: '2',
      date: '2026-05-02',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2078',
      personId: '2',
      date: '2026-05-03',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2079',
      personId: '2',
      date: '2026-05-04',
      entries: [
        {
          eid: '__total__',
          val: 28,
        },
      ],
    },
    {
      id: '2080',
      personId: '2',
      date: '2026-05-05',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2081',
      personId: '2',
      date: '2026-05-06',
      entries: [
        {
          eid: '__total__',
          val: 20,
        },
      ],
    },
    {
      id: '2082',
      personId: '2',
      date: '2026-05-07',
      entries: [
        {
          eid: '__total__',
          val: 32,
        },
      ],
    },
    {
      id: '2083',
      personId: '2',
      date: '2026-05-08',
      entries: [
        {
          eid: '__total__',
          val: 8,
        },
      ],
    },
    {
      id: '2084',
      personId: '2',
      date: '2026-05-09',
      entries: [
        {
          eid: '__total__',
          val: 228.88,
        },
      ],
    },
    {
      id: '2085',
      personId: '2',
      date: '2026-05-10',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2086',
      personId: '2',
      date: '2026-05-11',
      entries: [
        {
          eid: '__total__',
          val: 28,
        },
      ],
    },
    {
      id: '2087',
      personId: '2',
      date: '2026-05-13',
      entries: [
        {
          eid: '__total__',
          val: 38,
        },
      ],
    },
    {
      id: '2088',
      personId: '2',
      date: '2026-05-14',
      entries: [
        {
          eid: '__total__',
          val: 106.8,
        },
      ],
    },
    {
      id: '2089',
      personId: '2',
      date: '2026-05-15',
      entries: [
        {
          eid: '__total__',
          val: 24,
        },
      ],
    },
    {
      id: '2090',
      personId: '2',
      date: '2026-05-16',
      entries: [
        {
          eid: '__total__',
          val: 224.88,
        },
      ],
    },
    {
      id: '2091',
      personId: '2',
      date: '2026-05-17',
      entries: [
        {
          eid: '__total__',
          val: 16,
        },
      ],
    },
    {
      id: '2092',
      personId: '2',
      date: '2026-05-18',
      entries: [
        {
          eid: '__total__',
          val: 157.8,
        },
      ],
    },
    {
      id: '2093',
      personId: '2',
      date: '2026-05-19',
      entries: [
        {
          eid: '__total__',
          val: 20,
        },
      ],
    },
    {
      id: '2094',
      personId: '2',
      date: '2026-05-20',
      entries: [
        {
          eid: '__total__',
          val: 44,
        },
      ],
    },
    {
      id: '2095',
      personId: '2',
      date: '2026-05-22',
      entries: [
        {
          eid: '__total__',
          val: 100.44,
        },
      ],
    },
    {
      id: '2096',
      personId: '2',
      date: '2026-05-23',
      entries: [
        {
          eid: '__total__',
          val: 28,
        },
      ],
    },
    {
      id: '2097',
      personId: '2',
      date: '2026-05-24',
      entries: [
        {
          eid: '__total__',
          val: 20,
        },
      ],
    },
    {
      id: '2098',
      personId: '2',
      date: '2026-05-25',
      entries: [
        {
          eid: '__total__',
          val: 32,
        },
      ],
    },
    {
      id: '2099',
      personId: '2',
      date: '2026-05-26',
      entries: [
        {
          eid: '__total__',
          val: 36,
        },
      ],
    },
  ],
  movies: [
    {
      id: 'm6',
      title: 'The Dark Knight',
      rt: '94%',
      ratings: {
        '2': {
          score: 95,
        },
      },
    },
    {
      id: 'm7',
      title: 'Parasite',
      rt: '99%',
      ratings: {
        '2': {
          score: 94,
        },
      },
    },
    {
      id: 'm9',
      title: 'Avatar: The Way of Water',
      rt: '76%',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
    {
      id: 'm12',
      title: 'Mad Max: Fury Road',
      rt: '97%',
      ratings: {
        '2': {
          score: 89,
        },
      },
    },
    {
      id: 'm13',
      title: 'Mad Max Furiosa',
      rt: '90%',
      ratings: {
        '2': {
          score: 93,
        },
      },
    },
    {
      id: 'm15',
      title: 'Barbarian',
      rt: '92%',
      ratings: {
        '2': {
          score: 93,
        },
      },
    },
    {
      id: 'm16',
      title: 'Nope',
      rt: '83%',
      ratings: {
        '2': {
          score: 94,
        },
      },
    },
    {
      id: 'm18',
      title: 'Avatar: Fire and Ash',
      ratings: {
        '2': {
          score: 85,
        },
      },
    },
    {
      id: 'm23',
      title: 'One Battle After Another',
      rt: '94%',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
    {
      id: 'm30',
      title: 'Heretic',
      rt: '90%',
      ratings: {
        '2': {
          score: 91,
        },
      },
    },
    {
      id: 'm31',
      title: 'The Emperor&#39;s New Groove',
      rt: '86%',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
    {
      id: 'm32',
      title: 'Weapons',
      rt: '93%',
      ratings: {
        '2': {
          score: 91,
        },
      },
    },
    {
      id: 'm33',
      title: 'Evil Dead 2013',
      ratings: {
        '2': {
          score: 87,
        },
      },
    },
    {
      id: 'm35',
      title: 'Blade Runner 2049 (2017)',
      rt: '88%',
      ratings: {
        '2': {
          score: 89,
        },
      },
    },
    {
      id: 'm39',
      title: 'Bugonia',
      rt: '84%',
      ratings: {
        '2': {
          score: 91,
        },
      },
    },
    {
      id: 'm40',
      title: 'Hero',
      rt: '94%',
      ratings: {
        '2': {
          score: 88,
        },
      },
    },
    {
      id: 'm43',
      title: 'Us',
      rt: '93%',
      ratings: {
        '2': {
          score: 84,
        },
      },
    },
    {
      id: 'm44',
      title: 'Wake Up Dead Man: A Knives Out Mystery',
      rt: '94%',
      ratings: {
        '2': {
          score: 86,
        },
      },
    },
    {
      id: 'm46',
      title: 'Talk to me',
      rt: '94%',
      ratings: {
        '2': {
          score: 86,
        },
      },
    },
    {
      id: 'm54',
      title: 'Alita Battle Angel',
      rt: '61%',
      ratings: {
        '2': {
          score: 84,
        },
      },
    },
    {
      id: 'm55',
      title: 'NehZha2',
      rt: '92%',
      ratings: {
        '2': {
          score: 78,
        },
      },
    },
    {
      id: 'm56',
      title: 'Sinners',
      rt: '97%',
      ratings: {
        '2': {
          score: 82,
        },
      },
    },
    {
      id: 'm60',
      title: 'Predator: Badlands',
      rt: '86%',
      ratings: {
        '2': {
          score: 87,
        },
      },
    },
    {
      id: 'm63',
      title: 'KPop DH',
      rt: '96%',
      ratings: {
        '2': {
          score: 80,
        },
      },
    },
    {
      id: 'm65',
      title: 'The Revenant',
      rt: '78%',
      ratings: {
        '2': {
          score: 79,
        },
      },
    },
    {
      id: 'm66',
      title: 'Companion',
      ratings: {
        '2': {
          score: 80,
        },
      },
    },
    {
      id: 'm67',
      title: 'Anaconda',
      rt: '48%',
      ratings: {
        '2': {
          score: 85,
        },
      },
    },
    {
      id: 'm71',
      title: 'Alien Romulus',
      rt: '80%',
      ratings: {
        '2': {
          score: 79,
        },
      },
    },
    {
      id: 'm74',
      title: 'Pluribus S1',
      rt: '98%',
      ratings: {
        '2': {
          score: 82,
        },
      },
    },
    {
      id: 'm75',
      title: 'Frankenstein',
      rt: '85%',
      ratings: {
        '2': {
          score: 80,
        },
      },
    },
    {
      id: 'm78',
      title: 'The Batman',
      rt: '85%',
      ratings: {
        '2': {
          score: 74,
        },
      },
    },
    {
      id: 'm81',
      title: 'Prey',
      rt: '94%',
      ratings: {
        '2': {
          score: 75,
        },
      },
    },
    {
      id: 'm85',
      title: 'Good Fortune',
      rt: '79%',
      ratings: {
        '2': {
          score: 79,
        },
      },
    },
    {
      id: 'm86',
      title: 'Sisu',
      rt: '94%',
      ratings: {
        '2': {
          score: 77,
        },
      },
    },
    {
      id: 'm87',
      title: 'Blade 1',
      rt: '59%',
      ratings: {
        '2': {
          score: 83,
        },
      },
    },
    {
      id: 'm94',
      title: 'Van Helsing',
      rt: '34%',
      ratings: {
        '2': {
          score: 73,
        },
      },
    },
    {
      id: 'm96',
      title: 'Chainsaw Man: Reze Arc',
      rt: '96%',
      ratings: {
        '2': {
          score: 78,
        },
      },
    },
    {
      id: 'm97',
      title: 'Jumper',
      rt: '15%',
      ratings: {
        '2': {
          score: 75,
        },
      },
    },
    {
      id: 'm99',
      title: 'Speak No Evil (English)',
      rt: '83%',
      ratings: {
        '2': {
          score: 73,
        },
      },
    },
    {
      id: 'm100',
      title: 'League of Extrordinary GM',
      rt: '17%',
      ratings: {
        '2': {
          score: 72,
        },
      },
    },
    {
      id: 'm102',
      title: 'The Substance',
      rt: '89%',
      ratings: {
        '2': {
          score: 78,
        },
      },
    },
    {
      id: 'm103',
      title: 'mummy',
      ratings: {
        '2': {
          score: 70,
        },
      },
    },
    {
      id: 'm104',
      title: 'Mystery Men',
      rt: '59%',
      ratings: {
        '2': {
          score: 71,
        },
      },
    },
    {
      id: 'm107',
      title: 'Nobody2',
      rt: '77%',
      ratings: {
        '2': {
          score: 75,
        },
      },
    },
    {
      id: 'm110',
      title: 'Good Boy',
      rt: '90%',
      ratings: {
        '2': {
          score: 67,
        },
      },
    },
    {
      id: 'm111',
      title: 'Caught Stealing',
      rt: '84%',
      ratings: {
        '2': {
          score: 72,
        },
      },
    },
    {
      id: 'm112',
      title: 'Nobody',
      rt: '83%',
      ratings: {
        '2': {
          score: 65,
        },
      },
    },
    {
      id: 'm113',
      title: 'Minecraft Movie',
      rt: '47%',
      ratings: {
        '2': {
          score: 74,
        },
      },
    },
    {
      id: 'm115',
      title: 'Sisu 2',
      rt: '95%',
      ratings: {
        '2': {
          score: 61,
        },
      },
    },
    {
      id: 'm116',
      title: 'Mickey 17',
      rt: '78%',
      ratings: {
        '2': {
          score: 64,
        },
      },
    },
    {
      id: 'm118',
      title: 'The Fantastic Four: First Steps',
      rt: '86%',
      ratings: {
        '2': {
          score: 55,
        },
      },
    },
    {
      id: 'm119',
      title: 'Five Nights At Freddy&#39;s 2',
      rt: '16%',
      ratings: {
        '2': {
          score: 66,
        },
      },
    },
    {
      id: 'm120',
      title: 'I, Frankenstein',
      rt: '5%',
      ratings: {
        '2': {
          score: 57,
        },
      },
    },
    {
      id: 'm122',
      title: 'StrangerThings S5',
      rt: '84%',
      ratings: {
        '2': {
          score: 67,
        },
      },
    },
    {
      id: 'm123',
      title: 'TRON:Ares',
      rt: '53%',
      ratings: {
        '2': {
          score: 69,
        },
      },
    },
    {
      id: 'm124',
      title: 'CRIME 101',
      ratings: {
        '2': {
          score: 62,
        },
      },
    },
    {
      id: 'm125',
      title: 'The Watchers',
      rt: '32%',
      ratings: {
        '2': {
          score: 61,
        },
      },
    },
    {
      id: 'm126',
      title: 'Eddington',
      rt: '69%',
      ratings: {
        '2': {
          score: 51,
        },
      },
    },
    {
      id: 'm128',
      title: 'The Running Man 2025',
      rt: '63%',
      ratings: {
        '2': {
          score: 64,
        },
      },
    },
    {
      id: 'm131',
      title: 'Mortal Kombat II',
      ratings: {
        '2': {
          score: 87,
        },
      },
    },
    {
      id: 'm132',
      title: 'They Will Kill You',
      ratings: {
        '2': {
          score: 90,
        },
      },
    },
  ],
  watchlist: [
    {
      id: 'w0',
      title: 'The Big Lebowski',
      rt: '94%',
      votes: [],
    },
    {
      id: 'w1',
      title: '300',
      rt: '88%',
      votes: [],
    },
    {
      id: 'w2',
      title: 'No Country for Old Men',
      rt: '86%',
      votes: [],
    },
    {
      id: 'w3',
      title: 'Ex Machina',
      rt: '86%',
      votes: [],
    },
    {
      id: 'w4',
      title: '28 Days Later',
      rt: '85%',
      votes: [],
    },
    {
      id: 'w5',
      title: 'The Revenant',
      rt: '84%',
      votes: [],
    },
    {
      id: 'w6',
      title: 'Upgrade',
      rt: '83%',
      votes: [],
    },
    {
      id: 'w7',
      title: 'Arrival',
      rt: '82%',
      votes: [],
    },
    {
      id: 'w8',
      title: 'Arcadian',
      rt: '81%',
      votes: [],
    },
    {
      id: 'w9',
      title: 'Blade Runner 2049',
      rt: '81%',
      votes: [],
    },
    {
      id: 'w10',
      title: 'Dredd',
      rt: '78%',
      votes: [],
    },
    {
      id: 'w11',
      title: '28 Weeks Later',
      rt: '74%',
      votes: [],
    },
    {
      id: 'w12',
      title: 'Snowpiercer',
      rt: '73%',
      votes: [],
    },
    {
      id: 'w13',
      title: 'The Girl with All the Gifts',
      rt: '72%',
      votes: [],
    },
    {
      id: 'w14',
      title: 'Wyrmwood: Road of the Dead',
      rt: '70%',
      votes: [],
    },
    {
      id: 'w15',
      title: 'The Lobster',
      rt: '69%',
      votes: [],
    },
    {
      id: 'w16',
      title: 'Event Horizon',
      rt: '68%',
      votes: [],
    },
    {
      id: 'w17',
      title: 'Hereditary',
      rt: '67%',
      votes: [],
    },
    {
      id: 'w18',
      title: 'Annihilation',
      rt: '65%',
      votes: [],
    },
    {
      id: 'w19',
      title: 'Blade (Trilogy Average)',
      rt: '64%',
      votes: [],
    },
    {
      id: 'w20',
      title: 'Enemy',
      rt: '59%',
      votes: [],
    },
    {
      id: 'w21',
      title: 'The Road',
      rt: '58%',
      votes: [],
    },
    {
      id: 'w22',
      title: 'Dracula Untold',
      rt: '49%',
      votes: [],
    },
    {
      id: 'w23',
      title: 'Outlander (2008)',
      rt: '46%',
      votes: [],
    },
    {
      id: 'w24',
      title: 'Solomon Kane',
      rt: '45%',
      votes: [],
    },
    {
      id: 'w25',
      title: 'The Canal',
      rt: '44%',
      votes: [],
    },
    {
      id: 'w26',
      title: 'The Awakening',
      rt: '43%',
      votes: [],
    },
    {
      id: 'w27',
      title: 'Sahara',
      rt: '42%',
      votes: [],
    },
    {
      id: 'w28',
      title: 'The Hallow',
      rt: '41%',
      votes: [],
    },
    {
      id: 'w29',
      title: 'I, Frankenstein',
      rt: '35%',
      votes: [],
    },
    {
      id: 'w30',
      title: 'Legion',
      rt: '27%',
      votes: [],
    },
    {
      id: 'w31',
      title: 'The Pyramid',
      rt: '20%',
      votes: [],
    },
    {
      id: 'w32',
      title: 'Season of the Witch',
      rt: '18%',
      votes: [],
    },
    {
      id: 'w33',
      title: 'The Incredibles',
      votes: [],
    },
    {
      id: 'w34',
      title: 'terminators',
      votes: [],
    },
    {
      id: 'w35',
      title: 'resident evils',
      votes: [],
    },
    {
      id: 'w36',
      title: 'king kong',
      votes: [],
    },
    {
      id: 'w37',
      title: '10000 BC',
      votes: [],
    },
    {
      id: 'w38',
      title: 'excalibur',
      votes: [],
    },
    {
      id: 'w39',
      title: 'looper',
      votes: [],
    },
    {
      id: 'w40',
      title: 'Bring her back',
      votes: [],
    },
    {
      id: 'w41',
      title: 'prometheus',
      votes: [],
    },
    {
      id: 'w42',
      title: 'Shanghai Knights',
      votes: [],
    },
    {
      id: 'w43',
      title: 'Shanghai Noon',
      votes: [],
    },
    {
      id: 'w44',
      title: 'Dark Knight',
      votes: [],
    },
    {
      id: 'w45',
      title: 'soylent green',
      votes: [],
    },
    {
      id: 'w46',
      title: 'oddity',
      votes: [],
    },
    {
      id: 'w47',
      title: 'companion',
      votes: [],
    },
    {
      id: 'w48',
      title: 'ghost in the shell',
      votes: [],
    },
    {
      id: 'w49',
      title: 'sunshine',
      votes: [],
    },
    {
      id: 'w50',
      title: 'deer hunter',
      votes: [],
    },
    {
      id: 'w51',
      title: 'Evil dead 2013',
      votes: [],
    },
    {
      id: 'w52',
      title: 'Austin Powers',
      votes: [],
    },
    {
      id: 'w53',
      title: 'Waiting',
      votes: [],
    },
    {
      id: 'w54',
      title: 'Dodgeball',
      votes: [],
    },
    {
      id: 'w55',
      title: 'Die another day',
      votes: [],
    },
    {
      id: 'w56',
      title: 'Coyotes',
      votes: [],
    },
    {
      id: 'w57',
      title: 'The Shawshank Redemption',
      votes: [],
    },
    {
      id: 'w58',
      title: 'Tenet',
      votes: [],
    },
    {
      id: 'w59',
      title: 'shrek',
      votes: [],
    },
    {
      id: 'w60',
      title: 'spy kids',
      votes: [],
    },
    {
      id: 'w61',
      title: 'The Invisible Man',
      votes: [],
    },
    {
      id: 'w62',
      title: 'Cast Away',
      votes: [],
    },
    {
      id: 'w63',
      title: 'The Good, The Bad, The Ugly',
      votes: [],
    },
    {
      id: 'w64',
      title: 'Fight Club',
      votes: [],
    },
    {
      id: 'w65',
      title: 'The Matrix',
      votes: [],
    },
    {
      id: 'w66',
      title: 'Interstellar',
      votes: [],
    },
    {
      id: 'w67',
      title: 'American History X',
      votes: [],
    },
    {
      id: 'w68',
      title: 'The Usual Suspects',
      votes: [],
    },
    {
      id: 'w69',
      title: 'Memento',
      votes: [],
    },
    {
      id: 'w70',
      title: '2001: A Space Oddessy',
      votes: [],
    },
    {
      id: 'w71',
      title: 'Indiana Jones Movies',
      votes: [],
    },
    {
      id: 'w72',
      title: 'Wolf of Wall Street',
      votes: [],
    },
    {
      id: 'w73',
      title: 'There will be Blood',
      votes: [],
    },
    {
      id: 'w74',
      title: 'Shutter Island',
      votes: [],
    },
    {
      id: 'w75',
      title: '12 years a slave',
      votes: [],
    },
    {
      id: 'w76',
      title: 'million dollar baby',
      votes: [],
    },
    {
      id: 'w77',
      title: 'The Iron Giant',
      votes: [],
    },
    {
      id: 'w78',
      title: 'Gone Girl',
      votes: [],
    },
    {
      id: 'w79',
      title: 'The Sixth Sense',
      votes: [],
    },
    {
      id: 'w80',
      title: 'Resevoir Dogs',
      votes: [],
    },
    {
      id: 'w81',
      title: 'Eternal Sunshine of the Spotless Mind',
      votes: [],
    },
    {
      id: 'w82',
      title: 'The Truman Show',
      votes: [],
    },
    {
      id: 'w83',
      title: 'The Silence of the Lambs',
      votes: [],
    },
    {
      id: 'w84',
      title: 'Se7en',
      votes: [],
    },
    {
      id: 'w85',
      title: 'Requiem for a Dream',
      votes: [],
    },
    {
      id: 'w86',
      title: 'The Departed',
      votes: [],
    },
    {
      id: 'w87',
      title: 'Gangs of New York',
      votes: [],
    },
    {
      id: 'w88',
      title: 'Training Day',
      votes: [],
    },
    {
      id: 'w89',
      title: 'The Patriot',
      votes: [],
    },
    {
      id: 'w90',
      title: 'The Last of the Mohicans',
      votes: [],
    },
    {
      id: 'w91',
      title: 'Pulp fiction',
      votes: [],
    },
    {
      id: 'w92',
      title: 'Minority report',
      votes: [],
    },
    {
      id: 'w93',
      title: 'Neighbours',
      votes: [],
    },
    {
      id: 'w94',
      title: 'Superbad',
      votes: [],
    },
    {
      id: 'w95',
      title: 'They will kill you',
      votes: [],
    },
    {
      id: 'w96',
      title: 'GZ -1',
      votes: [],
    },
    {
      id: 'w97',
      title: 'BrodrickZilla',
      votes: [],
    },
    {
      id: 'w98',
      title: 'Breaking BadZilla',
      votes: [],
    },
    {
      id: 'w99',
      title: 'Boardroom Simulator',
      votes: [],
    },
    {
      id: 'w100',
      title: 'kinda of kindness',
      votes: [],
    },
  ],
}
