-- ============================================================================
-- ✅ RELAY SECURITY SWEEP, 2026-08-20. Migration: finalize_round_bounds_the_score_it_is_handed
--
-- The Render WebSocket relay (server/ws-server.js, wss://yaya-e2rw.onrender.com) was the last
-- unaudited surface — it sits outside Postgres, so none of the RLS work protects it, and it
-- holds SUPABASE_SERVICE_ROLE_KEY, which bypasses every policy.
--
-- ── FOUND: an unauthenticated stranger can write the Snake leaderboard ──────
-- The chain, every link verified in the source:
--   1. `new WebSocketServer({ server })` with NO verifyClient and NO origin check — the socket
--      accepts anyone on the internet.
--   2. The display name is self-declared on join, and the score is client-declared:
--      `st.lastScore = Number(msg.score)` straight off the wire, validated only as `typeof
--      === 'number'`.
--   3. When the round ends the relay calls finalize_round_rpc WITH THE SERVICE ROLE KEY.
--   4. That function did `INSERT INTO player_registry(player_name) ... ON CONFLICT DO NOTHING`
--      then selected the row BY NAME and wrote leaderboard + score_history + trophies to it.
--
-- So: pick a member's claimed handle as your name, report any score, finish the round. This is
-- a confused deputy — the relay's privilege used on behalf of an unauthenticated party — and it
-- BYPASSES the ownership rule submit_score got on 2026-08-19.
--
-- ── FIXED HERE (what is reachable from the database alone) ─────────────────
--   * the score is capped at 1,000,000, the same ceiling submit_score uses. There was no upper
--     bound at all, only `DELETE ... WHERE score < 0`, so 2,000,000,000 was writable.
--     Verified: a forged 2e9 round now writes 1000000.
--     Kept as a CAP not a DELETE, so dropping a row can't silently change who came second.
--   * EXECUTE re-revoked from public/anon/authenticated, granted to service_role only.
--     Verified: anon false, authenticated false, service_role true.
--   * Regression-checked: a normal 2-player round still ranks correctly, and replaying a
--     finalized round still returns the ORIGINAL results (a 999999 replay did not overwrite).
--
-- ── CLOSED 2026-08-20 (follow-up): the account is now protected ───────────
-- Migrations: finalize_round_will_not_touch_a_claimed_account,
--             finalize_round_is_callable_twice_in_one_transaction
--
-- Evan's steer: "snake scores are not a priority except the accounts and information tied to
-- them." That inverts the trade-off. Measured before choosing: only EIGHT multiplayer rounds
-- have ever been finalized. Plumbing a verified id through client + relay + a Render deploy to
-- preserve a path used eight times, for score recording that is explicitly not the priority,
-- is poor value — so the rule lives in the database and needs no deploy at all.
--
-- A CLAIMED handle (player_registry.user_id is not null) is not written unless the caller
-- supplies that owner's id in p_players[].userId. Unclaimed names are untouched, so casual and
-- signed-out multiplayer records exactly as before. The player still appears in the returned
-- placements — the round result stays honest about who played and who won; only the persistent
-- writes against somebody's account are withheld.
--
-- Verified on live data, all in one transaction and rolled back:
--   forged round, claimed handle, no vouch -> best stayed 225, history stayed 92 (NOTHING written)
--   same round WITH the owner's userId     -> best 999999, history 93 (vouched writes land)
--   an unclaimed casual name               -> recorded 42 normally
--   placements                             -> the skipped player is still listed, place 1
--
-- Forward compatible: nothing sends userId today. If the relay ever verifies tokens on join
-- (it already has verifyUser() for /ice), passing the id through restores claimed-handle
-- recording with no further database change. That is now a convenience upgrade, not a
-- security requirement.
--
-- ── ALSO FIXED: the function was not re-entrant ───────────────────────────
-- `CREATE TEMP TABLE ... ON COMMIT DROP` drops at COMMIT, not at function exit, so a second
-- call in the SAME transaction failed with "relation tmp_items already exists". Production
-- never saw it — the relay calls this once per HTTP request — but it cost me a test and would
-- cost anyone batching or retrying inside a transaction far more. Each call now drops first.
--
-- ── WHAT IS ACTUALLY LEFT ─────────────────────────────────────────────────
-- The database half is DONE. finalize_round_rpc already refuses to write to a claimed handle
-- unless the caller supplies that owner's id in p_players[].userId, and it already accepts that
-- field. So of the original four steps, 3 and 4 are complete.
--
-- Only the relay/client half remains, and it is now a CONVENIENCE upgrade, not a security fix:
--   1. the client sends its Supabase access token on WS join (it has one whenever signed in);
--   2. the relay verifies it — it ALREADY has this machinery, `verifyUser()`, used today for
--      the /ice TURN endpoint — binds the socket to a user id, and passes that id through.
--
-- Doing it RESTORES something rather than protecting anything: today a member playing
-- multiplayer under their own claimed handle has that round's score declined, because nobody
-- vouches for them. Worth it only if multiplayer scoring starts mattering — it has run eight
-- times ever.
--
-- No rollout ordering hazard any more. The enforcement already shipped, and it fails safe: a
-- payload without userId simply declines claimed handles rather than trusting them.
--
-- ── VERIFIED CLEAN in the relay ───────────────────────────────────────────
--   * service-role usage is only two paths: run_due_scheduled_trades (timer-driven, takes only
--     a batch size from env — NO client input reaches it) and finalize_round_rpc above.
--   * HTTP routes are properly gated: /usage is admin-only and asks the DATABASE's own
--     is_admin() rather than keeping a copy of the rule; /ice mints TURN credentials only for
--     a verified user and falls back to STUN otherwise, so an expired session degrades instead
--     of breaking calls. The Cloudflare TURN API token never leaves the server.
--   * DoS basics are present: 32 KB max message, name truncation at 64, chat capped at 300
--     chars with a 5-per-4s burst limit, room ids capped at 64.
--   * the token cache is per-token with a TTL and is cleared past 200 entries, so it cannot
--     grow unbounded.
--
-- ── STILL NOT SWEPT ───────────────────────────────────────────────────────
--   * WS connection rate/volume limiting (a stranger can still open sockets and create rooms)
--   * whether Render's own env/secret handling is as expected — outside this repo
-- ============================================================================

-- the change itself is the `least(..., v_max_score)` on the way into tmp_items, plus:
-- revoke all on function public.finalize_round_rpc(text, text, text, jsonb, jsonb)
--   from public, anon, authenticated;
-- grant execute on function public.finalize_round_rpc(text, text, text, jsonb, jsonb)
--   to service_role;
