-- =====================================================
-- db-schema-summary.sql
-- =====================================================
-- Read-only snapshot of the Supabase public schema.
-- Source of truth for development & Copilot context.
--
-- ❗ DO NOT EXECUTE THIS FILE
-- ❗ DO NOT EDIT DATABASE BY HAND BASED ON THIS FILE
--
-- Last verified: 2025-03-XX
-- Schema: public
-- =====================================================


-- =====================================================
-- TABLE: public.player_registry
-- =====================================================
-- Purpose:
--   Canonical registry of unique player identities.
--   Player names are case-insensitive (citext).

-- Columns:
-- id            BIGINT PRIMARY KEY
--               DEFAULT nextval('player_registry_id_seq')
-- player_name   CITEXT NOT NULL UNIQUE
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()

-- Constraints:
-- player_registry_pkey                PRIMARY KEY (id)
-- player_registry_player_name_key     UNIQUE (player_name)

-- Indexes:
-- player_registry_pkey
-- player_registry_player_name_key
-- ux_player_registry_name_ci          (citext index)

-- Referenced by:
-- leaderboard.player_id
-- score_history.player_id


-- =====================================================
-- TABLE: public.leaderboard
-- =====================================================
-- Purpose:
--   Stores the BEST score per player per game_mode.
--   One row per (player_id, game_mode).

-- Columns:
-- id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
-- score         INTEGER NULL
-- player_name   TEXT NULL DEFAULT ''
-- game_mode     TEXT NOT NULL DEFAULT 'solo'
-- apples_eaten  INTEGER NOT NULL DEFAULT 0
-- time_elapsed  INTEGER NOT NULL DEFAULT 0
-- player_id     BIGINT NOT NULL REFERENCES player_registry(id)

-- Constraints:
-- leaderboard_pkey              PRIMARY KEY (id)
-- leaderboard_player_id_fkey    FOREIGN KEY (player_id)
-- fk_leaderboard_player         FOREIGN KEY (player_id)

-- Indexes:
-- leaderboard_pkey
-- ux_leaderboard_player_mode    UNIQUE (player_id, game_mode)

-- Triggers:
-- leaderboard_best_score
--   BEFORE UPDATE
--   EXECUTE FUNCTION enforce_best_score()

-- Notes:
-- - RLS enabled
-- - score may be NULL during placeholder creation
-- - enforce_best_score prevents score regression


-- =====================================================
-- TABLE: public.score_history
-- =====================================================
-- Purpose:
--   Immutable append-only log of ALL completed games.

-- Columns:
-- id            BIGINT PRIMARY KEY DEFAULT nextval('score_history_id_seq')
-- player_name   TEXT NOT NULL
-- score         INTEGER NOT NULL CHECK (score >= 0)
-- game_mode     TEXT NOT NULL DEFAULT 'solo'
-- apples_eaten  INTEGER NOT NULL DEFAULT 0
-- time_elapsed  INTEGER NOT NULL DEFAULT 0
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
-- player_id     BIGINT NOT NULL REFERENCES player_registry(id)

-- Constraints:
-- score_history_pkey
-- score_history_player_id_fkey
-- fk_scorehistory_player
-- score_history_score_check

-- Indexes:
-- score_history_pkey

-- Notes:
-- - Written by finalize_round_rpc (multiplayer)
-- - Also written by legacy solo submitScore path (to be unified)


-- =====================================================
-- TABLE: public.round_results
-- =====================================================
-- Purpose:
--   Canonical record of finalized multiplayer rounds.

-- Columns:
-- id            BIGINT PRIMARY KEY DEFAULT nextval('round_results_id_seq')
-- room_id       TEXT NOT NULL
-- round_id      TEXT NOT NULL
-- game_mode     TEXT NOT NULL DEFAULT 'survival'
-- results       JSONB NOT NULL
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()

-- Constraints:
-- round_results_pkey
-- round_results_room_id_round_id_key   UNIQUE (room_id, round_id)

-- Indexes:
-- round_results_pkey
-- round_results_room_id_round_id_key

-- Notes:
-- - Written exclusively by finalize_round_rpc
-- - round_id originates from ws-server.js
-- - Idempotency enforced by UNIQUE(room_id, round_id)


-- =====================================================
-- TABLE: public.trophies
-- =====================================================
-- Purpose:
--   Stores awards associated with leaderboard entries.

-- Columns:
-- id              BIGINT PRIMARY KEY
-- leaderboard_id  BIGINT NOT NULL REFERENCES leaderboard(id)
-- trophy_name     TEXT NOT NULL
-- awarded_at      TIMESTAMPTZ NOT NULL DEFAULT now()

-- Constraints:
-- trophies_pkey
-- trophies_leaderboard_id_fkey
-- fk_trophies_leaderboard
--   ON DELETE CASCADE

-- Indexes:
-- trophies_pkey

-- Notes:
-- - Written by finalize_round_rpc
-- - RLS currently disabled


-- =====================================================
-- VIEW: public.leaderboard_with_trophies
-- =====================================================
-- Purpose:
--   Read-only convenience view for UI display.

-- Columns:
-- id            BIGINT
-- player_name   TEXT
-- score         INTEGER
-- created_at    TIMESTAMPTZ
-- trophies      JSON

-- Notes:
-- - Joins leaderboard and trophies
-- - Not written to directly
