-- =====================================================
-- db-schema-summary.sql
-- =====================================================
-- Read-only snapshot of the Supabase public schema.
-- Source of truth for development & Copilot context.
--
-- ❗ DO NOT EXECUTE THIS FILE
-- ❗ DO NOT EDIT DATABASE BY HAND BASED ON THIS FILE
--
-- Last verified: 2026-06-07
-- Schemas: public, finance
-- =====================================================


-- =====================================================
-- TABLE: public.player_registry
-- =====================================================
-- Purpose:
--   Canonical registry of unique player identities.
--   Player names are case-insensitive (citext).

-- Columns:
-- id            BIGINT PRIMARY KEY
--               DEFAULT nextval('player_registry_id_seq')
-- player_name   CITEXT NOT NULL UNIQUE
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()

-- Constraints:
-- player_registry_pkey                PRIMARY KEY (id)
-- player_registry_player_name_key     UNIQUE (player_name)

-- Indexes:
-- player_registry_pkey
-- player_registry_player_name_key
-- ux_player_registry_name_ci          (citext index)

-- Referenced by:
-- leaderboard.player_id
-- score_history.player_id


-- =====================================================
-- TABLE: public.leaderboard
-- =====================================================
-- Purpose:
--   Stores the BEST score per player per game_mode.
--   One row per (player_id, game_mode).

-- Columns:
-- id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
-- score         INTEGER NULL
-- player_name   TEXT NULL DEFAULT ''
-- game_mode     TEXT NOT NULL DEFAULT 'solo'
-- apples_eaten  INTEGER NOT NULL DEFAULT 0
-- time_elapsed  INTEGER NOT NULL DEFAULT 0
-- player_id     BIGINT NOT NULL REFERENCES player_registry(id)

-- Constraints:
-- leaderboard_pkey              PRIMARY KEY (id)
-- leaderboard_player_id_fkey    FOREIGN KEY (player_id)
-- fk_leaderboard_player         FOREIGN KEY (player_id)

-- Indexes:
-- leaderboard_pkey
-- ux_leaderboard_player_mode    UNIQUE (player_id, game_mode)

-- Triggers:
-- leaderboard_best_score
--   BEFORE UPDATE
--   EXECUTE FUNCTION enforce_best_score()

-- Notes:
-- - RLS enabled
-- - score may be NULL during placeholder creation
-- - enforce_best_score prevents score regression


-- =====================================================
-- TABLE: public.score_history
-- =====================================================
-- Purpose:
--   Immutable append-only log of ALL completed games.

-- Columns:
-- id            BIGINT PRIMARY KEY DEFAULT nextval('score_history_id_seq')
-- player_name   TEXT NOT NULL
-- score         INTEGER NOT NULL CHECK (score >= 0)
-- game_mode     TEXT NOT NULL DEFAULT 'solo'
-- apples_eaten  INTEGER NOT NULL DEFAULT 0
-- time_elapsed  INTEGER NOT NULL DEFAULT 0
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
-- player_id     BIGINT NOT NULL REFERENCES player_registry(id)

-- Constraints:
-- score_history_pkey
-- score_history_player_id_fkey
-- fk_scorehistory_player
-- score_history_score_check

-- Indexes:
-- score_history_pkey

-- Notes:
-- - Written by finalize_round_rpc (multiplayer)
-- - Also written by legacy solo submitScore path (to be unified)


-- =====================================================
-- TABLE: public.round_results
-- =====================================================
-- Purpose:
--   Canonical record of finalized multiplayer rounds.

-- Columns:
-- id            BIGINT PRIMARY KEY DEFAULT nextval('round_results_id_seq')
-- room_id       TEXT NOT NULL
-- round_id      TEXT NOT NULL
-- game_mode     TEXT NOT NULL DEFAULT 'survival'
-- results       JSONB NOT NULL
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()

-- Constraints:
-- round_results_pkey
-- round_results_room_id_round_id_key   UNIQUE (room_id, round_id)

-- Indexes:
-- round_results_pkey
-- round_results_room_id_round_id_key

-- Notes:
-- - Written exclusively by finalize_round_rpc
-- - round_id originates from ws-server.js
-- - Idempotency enforced by UNIQUE(room_id, round_id)


-- =====================================================
-- TABLE: public.trophies
-- =====================================================
-- Purpose:
--   Stores awards associated with leaderboard entries.

-- Columns:
-- id              BIGINT PRIMARY KEY
-- leaderboard_id  BIGINT NOT NULL REFERENCES leaderboard(id)
-- trophy_name     TEXT NOT NULL
-- awarded_at      TIMESTAMPTZ NOT NULL DEFAULT now()

-- Constraints:
-- trophies_pkey
-- trophies_leaderboard_id_fkey
-- fk_trophies_leaderboard
--   ON DELETE CASCADE

-- Indexes:
-- trophies_pkey

-- Notes:
-- - Written by finalize_round_rpc
-- - RLS currently disabled


-- =====================================================
-- VIEW: public.leaderboard_with_trophies
-- =====================================================
-- Purpose:
--   Read-only convenience view for UI display.

-- Columns:
-- id            BIGINT
-- player_name   TEXT
-- score         INTEGER
-- created_at    TIMESTAMPTZ
-- trophies      JSON

-- Notes:
-- - Joins leaderboard and trophies
-- - Not written to directly


-- =====================================================
-- FINANCE SCHEMA
-- =====================================================
-- All tables live in the `finance` schema.
-- PostgREST only exposes `public`, so all access is
-- via public.* RPC proxies defined in supabase-rpcs.sql.
-- RLS: every table has user_id = auth.uid() policies.
-- =====================================================


-- =====================================================
-- TABLE: finance.family_accounts
-- =====================================================
-- Purpose:
--   One row per family investment account (e.g. "Alice", "Bob").
--   Owned per-user; 32+ accounts expected.

-- Columns:
-- id            UUID PRIMARY KEY DEFAULT gen_random_uuid()
-- user_id       UUID NOT NULL REFERENCES auth.users(id)
-- display_name  TEXT NOT NULL
-- created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
-- updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()

-- Constraints:
-- family_accounts_pkey            PRIMARY KEY (id)
-- family_accounts_user_id_fkey    FOREIGN KEY (user_id) REFERENCES auth.users(id)

-- Notes:
-- - RLS: SELECT/INSERT/UPDATE/DELETE all require user_id = auth.uid()
-- - Written via public.insert_family_account(payload) RPC
-- - Read via public.get_family_accounts(uid) RPC


-- =====================================================
-- TABLE: finance.executed_trades
-- =====================================================
-- Purpose:
--   Immutable record of every buy/sell trade executed.
--   ~200 historical trades + ongoing daily dollar-a-day trades.

-- Columns:
-- id             UUID PRIMARY KEY DEFAULT gen_random_uuid()
-- user_id        UUID NOT NULL REFERENCES auth.users(id)
-- asset_symbol   TEXT NOT NULL
-- asset_type     TEXT
-- platform       TEXT
-- execution_time TIMESTAMPTZ NOT NULL DEFAULT now()
-- dollar_amount  NUMERIC NOT NULL CHECK (dollar_amount > 0)
-- price          NUMERIC NOT NULL CHECK (price > 0)
-- units_acquired NUMERIC NOT NULL CHECK (units_acquired > 0)
-- fee            NUMERIC NOT NULL DEFAULT 0 CHECK (fee >= 0)
-- created_at     TIMESTAMPTZ NOT NULL DEFAULT now()

-- Notes:
-- - RLS: user_id = auth.uid()
-- - Written via public.insert_executed_trade(payload) or
--   public.insert_trade_even_split(payload)
-- - Read via public.get_executed_trades(uid) RPC


-- =====================================================
-- TABLE: finance.allocations
-- =====================================================
-- Purpose:
--   Maps fractional units from an executed trade to each family account.
--   Sum of units_allocated across all rows for a trade equals trade.units_acquired.

-- Columns:
-- id                  UUID PRIMARY KEY DEFAULT gen_random_uuid()
-- user_id             UUID NOT NULL REFERENCES auth.users(id)
-- family_account_id   UUID NOT NULL REFERENCES finance.family_accounts(id)
-- executed_trade_id   UUID NOT NULL REFERENCES finance.executed_trades(id)
-- units_allocated     NUMERIC NOT NULL CHECK (units_allocated > 0)
-- created_at          TIMESTAMPTZ NOT NULL DEFAULT now()

-- Notes:
-- - RLS: user_id = auth.uid()
-- - Written by public.insert_trade_even_split(payload) — even split across all accounts
-- - Read via public.get_allocations(uid) RPC


-- =====================================================
-- TABLE: finance.scheduled_trades
-- =====================================================
-- Purpose:
--   Queue of future trades to be executed automatically.
--   Processed by public.run_due_scheduled_trades(limit_count) RPC.

-- Columns:
-- id                  UUID PRIMARY KEY DEFAULT gen_random_uuid()
-- user_id             UUID NOT NULL
-- payload             JSONB NOT NULL
-- schedule_at         TIMESTAMPTZ NOT NULL
-- status              TEXT NOT NULL DEFAULT 'pending'
--                       CHECK (status IN ('pending','processing','done','failed'))
-- attempts            INT NOT NULL DEFAULT 0
-- last_error          TEXT
-- executed_trade_id   UUID
-- created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
-- updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
-- executed_at         TIMESTAMPTZ

-- Indexes:
-- idx_scheduled_trades_user            (user_id)
-- idx_scheduled_trades_pending_time    (status, schedule_at)

-- Notes:
-- - Written via public.schedule_trade_even_split(payload) RPC
-- - Processed by public.run_due_scheduled_trades(limit_count) (cron/server)
